package
{
   import Playtomic.Log;
   import §_-CI§.§_-EI§;
   import com.reintroducing.sound.SoundManager;
   import fl.lang.Locale;
   import flash.display.MovieClip;
   import flash.events.ContextMenuEvent;
   import flash.events.Event;
   import flash.net.URLRequest;
   import flash.net.trace;
   import flash.ui.ContextMenu;
   import flash.ui.ContextMenuItem;
   import flash.utils.Dictionary;
   import mochi.as3.MochiAd;
   
   public dynamic class Defense extends MovieClip
   {
       
      
      public var tooltipsStatus:Boolean;
      
      public var soundFxStatus:Boolean = true;
      
      public var soundMusicStatus:Boolean = true;
      
      private var intros:MovieClip;
      
      private var introTime:int = 365;
      
      private var introTimeCounter:int = 0;
      
      public var agi;
      
      public var kongregate;
      
      private var devKey:String = "3d6ddc62dd9beaf78afac4022209705a";
      
      private var §_-Kl§:String = "kingdom-rush";
      
      public var onlineData:Object;
      
      public var mpc:Boolean;
      
      public var onlineSlotNumber:int;
      
      private var missileParticlesMax:int = 150;
      
      public var missileParticlesPool:Dictionary;
      
      private var fireballParticlesMax:int = 150;
      
      public var fireballParticlesPool:Dictionary;
      
      private var veznanParticlesMax:int = 150;
      
      public var veznanParticlesPool:Dictionary;
      
      public function Defense()
      {
         super();
         Log.View(939624,"0cbe3a620afb43f0",loaderInfo.loaderURL);
         var _loc1_:ContextMenu = new ContextMenu();
         _loc1_.hideBuiltInItems();
         var _loc2_:* = new ContextMenuItem("More Games: www.armorgames.com");
         var _loc3_:* = new ContextMenuItem("©" + String(§_-EI§.§_-7r§(864,828)));
         _loc2_.addEventListener(ContextMenuEvent.MENU_ITEM_SELECT,this.openArmorLink,false,0,true);
         _loc3_.addEventListener(ContextMenuEvent.MENU_ITEM_SELECT,this.openLink,false,0,true);
         _loc1_.customItems.push(_loc2_,_loc3_);
         this.contextMenu = _loc1_;
         this.addEventListener(Event.ADDED_TO_STAGE,this.init);
         MochiAd.showPreGameAd({
            "clip":this,
            "id":"bf76facdfccdd989",
            "res":"700x600",
            "ad_finished":this.start
         });
         this.mpc = true;
      }
      
      public function start() : void
      {
         this.§_-CP§();
      }
      
      public function openArmorLink(param1:ContextMenuEvent) : void
      {
         var _loc2_:String = §_-EI§.§_-7r§(862,826);
         var _loc3_:URLRequest = new URLRequest(_loc2_);
         trace(_loc3_,"_blank");
      }
      
      public function openLink(param1:ContextMenuEvent) : void
      {
         var _loc2_:String = §_-EI§.§_-7r§(861,825);
         var _loc3_:URLRequest = new URLRequest(_loc2_);
         trace(_loc3_,"_blank");
      }
      
      public function init(param1:Event) : void
      {
         this.stop();
      }
      
      private function _initContent(param1:Event) : void
      {
      }
      
      public function §_-CP§() : void
      {
         this.gotoAndStop(2);
         this.createFireballParticlesPool();
         this.createMissileParticlesPool();
         this.createVeznanParticlesPool();
         this.intros = new Intros();
         this.intros.addEventListener(Event.ENTER_FRAME,this.introFrame,false,0,true);
         this.addChild(this.intros);
      }
      
      private function introFrame(param1:Event) : void
      {
         if(this.introTimeCounter < this.introTime)
         {
            this.introTimeCounter++;
            return;
         }
         this.intros.removeEventListener(Event.ENTER_FRAME,this.introFrame);
         this.removeChild(this.intros);
         this.intros = null;
         this.initGame();
      }
      
      public function initGame() : void
      {
         this.tooltipsStatus = true;
         this.loadLangs();
         this.loadSounds();
         this.showMainMenu();
      }
      
      public function showMainMenu() : void
      {
         this.addChildAt(new MainMenu(),0);
      }
      
      public function loadGame(param1:String) : void
      {
         this.addChildAt(new Game(this,param1),0);
      }
      
      public function §_-Bm§() : void
      {
         this.addChildAt(new MenuCredits(this),0);
      }
      
      public function showTransition(param1:LevelSelect = null, param2:Level = null, param3:MainMenu = null, param4:Map = null, param5:MainMenu = null, param6:MenuCredits = null, param7:EndGame = null) : void
      {
         SoundManager.getInstance().stopSound("gui_transition_door");
         SoundManager.getInstance().playSound("gui_transition_door",0.6,0,0);
         this.addChild(new TransitionScreen(param1,param2,param3,param4,param5,param6,param7));
      }
      
      public function showEndGame(param1:Level) : void
      {
         this.addChild(new EndGame(param1));
      }
      
      public function resetSounds() : void
      {
         SoundManager.getInstance().removeAllTmpSounds();
      }
      
      public function loadSounds() : void
      {
         SoundManager.getInstance().addLibrarySound(Music_MainMenu,"music_main_menu");
         SoundManager.getInstance().addLibrarySound(§_-ES§,"music_map");
         SoundManager.getInstance().addLibrarySound(§_-Gn§,"music_pre_battle");
         SoundManager.getInstance().addLibrarySound(§_-Ty§,"music_battle");
         SoundManager.getInstance().addLibrarySound(§_-9f§,"music_boss_fight");
         SoundManager.getInstance().addLibrarySound(§_-3f§,"music_battle_veznan");
         SoundManager.getInstance().addLibrarySound(§_-Km§,"music_end_game");
         SoundManager.getInstance().addLibrarySound(§_-MR§,"music_suspense");
         SoundManager.getInstance().addLibrarySound(§_-TC§,"gui_quest_completed");
         SoundManager.getInstance().addLibrarySound(§_-JG§,"gui_win_stars");
         SoundManager.getInstance().addLibrarySound(§_-JG§,"gui_win_stars2");
         SoundManager.getInstance().addLibrarySound(§_-JG§,"gui_win_stars3");
         SoundManager.getInstance().addLibrarySound(§_-0-§,"gui_victory_cheer");
         SoundManager.getInstance().addLibrarySound(§_-Tb§,"gui_map_new_flag");
         SoundManager.getInstance().addLibrarySound(§_-Tb§,"gui_map_new_flag");
         SoundManager.getInstance().addLibrarySound(§_-EL§,"gui_map_road");
         SoundManager.getInstance().addLibrarySound(§_-Lv§,"gui_next_wave_ready");
         SoundManager.getInstance().addLibrarySound(§_-Ra§,"gui_next_wave_reward");
         SoundManager.getInstance().addLibrarySound(§_-T5§,"gui_loose_life1");
         SoundManager.getInstance().addLibrarySound(§_-T5§,"gui_loose_life2");
         SoundManager.getInstance().addLibrarySound(§_-T5§,"gui_loose_life3");
         SoundManager.getInstance().addLibrarySound(§_-T5§,"gui_loose_life4");
         SoundManager.getInstance().addLibrarySound(§_-U2§,"gui_quest_failed");
         SoundManager.getInstance().addLibrarySound(Sound_GUIButtonCommon,"gui_button_common");
         SoundManager.getInstance().addLibrarySound(Sound_GUIShowHideMenues,"gui_show_hide_menues");
         SoundManager.getInstance().addLibrarySound(Sound_GUIBuyUpgrade,"gui_buy_upgrade");
         SoundManager.getInstance().addLibrarySound(§_-R5§,"gui_transition_door");
         SoundManager.getInstance().addLibrarySound(§_-P5§,"gui_open_tower_menu");
         SoundManager.getInstance().addLibrarySound(§_-HN§,"gui_mouse_over_tower");
         SoundManager.getInstance().addLibrarySound(Sound_GUIMouseOverTowerIcon,"gui_mouse_over_tower_common");
         SoundManager.getInstance().addLibrarySound(§_-4E§,"gui_mouse_over_metallic");
         SoundManager.getInstance().addLibrarySound(Sound_AchievementWin,"gui_achievement_win");
         SoundManager.getInstance().addLibrarySound(§_-9g§,"gui_notification_close");
         SoundManager.getInstance().addLibrarySound(Sound_NotificationSecondLevel,"gui_notification_popup");
         SoundManager.getInstance().addLibrarySound(Sound_NotificationOpen,"gui_notification_open");
         SoundManager.getInstance().addLibrarySound(Sound_NotificationPaperOver,"gui_notification_over");
         SoundManager.getInstance().addLibrarySound(Sound_NotificationPaperOver2,"gui_notification_over2");
         SoundManager.getInstance().addLibrarySound(§_-0v§,"wave_incoming");
         SoundManager.getInstance().addLibrarySound(§_-6W§,"gui_spell_refresh");
         SoundManager.getInstance().addLibrarySound(§_-RG§,"gui_spell_select");
         SoundManager.getInstance().addLibrarySound(§_-U-§,"gui_rally_point_placed");
         SoundManager.getInstance().addLibrarySound(§_-Ix§,"tower_building");
         SoundManager.getInstance().addLibrarySound(Sound_TowerUpgrade,"tower_upgrade");
         SoundManager.getInstance().addLibrarySound(§_-8j§,"tower_sell");
         SoundManager.getInstance().addLibrarySound(§_-0I§,"tower_archer_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherTaunt1,"tower_archer_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherTaunt2,"tower_archer_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-7E§,"tower_archer_musketeer_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherMusketeerTaunt1,"tower_archer_musketeer_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherMusketeerTaunt2,"tower_archer_musketeer_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-BK§,"tower_archer_musketeer_sniper");
         SoundManager.getInstance().addLibrarySound(§_-2Z§,"tower_archer_ranger_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherRangerTaunt1,"tower_archer_ranger_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerArcherRangerTaunt2,"tower_archer_ranger_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-1Q§,"tower_mage_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerMageTaunt1,"tower_mage_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerMageTaunt2,"tower_mage_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-3i§,"tower_mage_arcane_ready");
         SoundManager.getInstance().addLibrarySound(§_-O7§,"tower_mage_arcane_teleport");
         SoundManager.getInstance().addLibrarySound(§_-4§,"tower_mage_arcane_desintegrate");
         SoundManager.getInstance().addLibrarySound(§_-TN§,"tower_mage_sorcerer_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerMageSorcererTaunt1,"tower_mage_sorcerer_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerMageSorcererTaunt2,"tower_mage_sorcerer_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-Ar§,"tower_mage_sorcerer_elemental_rally");
         SoundManager.getInstance().addLibrarySound(§_-Ju§,"tower_engineer_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerEngineerTaunt1,"tower_engineer_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerEngineerTaunt2,"tower_engineer_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-K5§,"tower_engineer_bfg_ready");
         SoundManager.getInstance().addLibrarySound(§_-OD§,"tower_engineer_bfg_cluster");
         SoundManager.getInstance().addLibrarySound(§_-SX§,"tower_engineer_bfg_missile");
         SoundManager.getInstance().addLibrarySound(§_-QX§,"tower_engineer_tesla_ready");
         SoundManager.getInstance().addLibrarySound(§_-1m§,"tower_engineer_tesla_overcharge");
         SoundManager.getInstance().addLibrarySound(§_-HI§,"tower_engineer_tesla_charged_bolt");
         SoundManager.getInstance().addLibrarySound(Sound_TowerEngineerTeslaChargedBolt2,"tower_engineer_tesla_charged_bolt2");
         SoundManager.getInstance().addLibrarySound(Sound_TowerEngineerTeslaChargedBolt3,"tower_engineer_tesla_charged_bolt3");
         SoundManager.getInstance().addLibrarySound(§_-Gh§,"tower_soldier_ready");
         SoundManager.getInstance().addLibrarySound(§_-Ru§,"tower_soldier_move");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierTaunt1,"tower_soldier_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierTaunt2,"tower_soldier_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-7B§,"tower_soldier_barbarian_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierBarbarianTaunt1,"tower_soldier_barbarian_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierBarbarianTaunt2,"tower_soldier_barbarian_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-I3§,"tower_soldier_barbarian_move");
         SoundManager.getInstance().addLibrarySound(§_-Sh§,"tower_soldier_paladin_ready");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierPaladinTaunt1,"tower_soldier_paladin_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_TowerSoldierPaladinTaunt2,"tower_soldier_paladin_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-6C§,"tower_soldier_paladin_move");
         SoundManager.getInstance().addLibrarySound(Sound_ElfTaunt1,"tower_soldier_elf_taunt1");
         SoundManager.getInstance().addLibrarySound(Sound_ElfTaunt2,"tower_soldier_elf_taunt2");
         SoundManager.getInstance().addLibrarySound(§_-5Q§,"tower_soldier_sasquash_ready");
         SoundManager.getInstance().addLibrarySound(§null§,"tower_soldier_sasquash_rally");
         SoundManager.getInstance().addLibrarySound(Sound_Reinforcements1,"reinforcement_event1");
         SoundManager.getInstance().addLibrarySound(Sound_Reinforcements2,"reinforcement_event2");
         SoundManager.getInstance().addLibrarySound(Sound_Reinforcements3,"reinforcement_event3");
         SoundManager.getInstance().addLibrarySound(Sound_Reinforcements4,"reinforcement_event4");
         SoundManager.getInstance().addLibrarySound(Sound_TeslaAttack1,"tesla_attack_1");
         SoundManager.getInstance().addLibrarySound(Sound_TeslaAttack2,"tesla_attack_2");
         SoundManager.getInstance().addLibrarySound(Sound_TeslaAttack1,"tesla_attack_3");
         SoundManager.getInstance().addLibrarySound(Sound_TeslaAttack2,"tesla_attack_4");
         SoundManager.getInstance().addLibrarySound(§_-Ex§,"tower_open_door");
         SoundManager.getInstance().addLibrarySound(§_-DS§,"pc_gnome_cash");
         SoundManager.getInstance().addLibrarySound(§_-2t§,"pc_thunder");
         SoundManager.getInstance().addLibrarySound(§_-41§,"sheep");
         SoundManager.getInstance().addLibrarySound(§_-3m§,"soldier_fight_1");
         SoundManager.getInstance().addLibrarySound(§_-Mi§,"attack_wolf");
         SoundManager.getInstance().addLibrarySound(Sound_WolfAttack2,"attack_wolf2");
         SoundManager.getInstance().addLibrarySound(§_-24§,"attack_spider");
         SoundManager.getInstance().addLibrarySound(Sound_SpiderAttack2,"attack_spider2");
         SoundManager.getInstance().addLibrarySound(§_-7G§,"juggernaut_death");
         SoundManager.getInstance().addLibrarySound(§_-3B§,"jt_attack");
         SoundManager.getInstance().addLibrarySound(§_-K§,"jt_death");
         SoundManager.getInstance().addLibrarySound(§_-NU§,"jt_eat");
         SoundManager.getInstance().addLibrarySound(§_-LL§,"jt_explode");
         SoundManager.getInstance().addLibrarySound(§_-3C§,"jt_rest");
         SoundManager.getInstance().addLibrarySound(Sound_HitIce1,"jt_hit_ice1");
         SoundManager.getInstance().addLibrarySound(Sound_HitIce2,"jt_hit_ice2");
         SoundManager.getInstance().addLibrarySound(Sound_HitIce3,"jt_hit_ice3");
         SoundManager.getInstance().addLibrarySound(Sound_DemonPortalSumon,"veznan_portals_summon");
         SoundManager.getInstance().addLibrarySound(§_-Rf§,"veznan_portals_teleport_in_1");
         SoundManager.getInstance().addLibrarySound(§_-Rf§,"veznan_portals_teleport_in_2");
         SoundManager.getInstance().addLibrarySound(§_-Rf§,"veznan_portals_teleport_in_3");
         SoundManager.getInstance().addLibrarySound(§_-Rf§,"veznan_portals_teleport_in_4");
         SoundManager.getInstance().addLibrarySound(§_-W§,"veznan_hold_cast");
         SoundManager.getInstance().addLibrarySound(§_-AG§,"veznan_hold_hit_1");
         SoundManager.getInstance().addLibrarySound(§_-AG§,"veznan_hold_hit_2");
         SoundManager.getInstance().addLibrarySound(§_-AG§,"veznan_hold_hit_3");
         SoundManager.getInstance().addLibrarySound(§_-AG§,"veznan_hold_hit_4");
         SoundManager.getInstance().addLibrarySound(§_-CB§,"veznan_hold_dissipate_1");
         SoundManager.getInstance().addLibrarySound(§_-CB§,"veznan_hold_dissipate_2");
         SoundManager.getInstance().addLibrarySound(§_-CB§,"veznan_hold_dissipate_3");
         SoundManager.getInstance().addLibrarySound(§_-CB§,"veznan_hold_dissipate_4");
         SoundManager.getInstance().addLibrarySound(§_-Ow§,"veznan_hold_hum");
         SoundManager.getInstance().addLibrarySound(§_-EO§,"veznan_hold_trap");
         SoundManager.getInstance().addLibrarySound(§_-HD§,"veznan_area_attack_1");
         SoundManager.getInstance().addLibrarySound(§_-HD§,"veznan_area_attack_2");
         SoundManager.getInstance().addLibrarySound(§_-Pk§,"veznan_demon_fire");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyVeznanToDemon,"veznan_to_demon");
         SoundManager.getInstance().addLibrarySound(§_-0U§,"veznan_tsung");
         SoundManager.getInstance().addLibrarySound(§_-Qv§,"veznan_death");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowHit2,"arrow_hit_2");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowHit3,"arrow_hit_3");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease2,"arrow_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease3,"arrow_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease2,"arrow_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease3,"arrow_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease2,"arrow_pool_5");
         SoundManager.getInstance().addLibrarySound(Sound_ArrowRelease3,"arrow_pool_6");
         SoundManager.getInstance().addLibrarySound(§_-LN§,"axe_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-LN§,"axe_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-LN§,"axe_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-LN§,"axe_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-EE§,"shootgun_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-EE§,"shootgun_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-EE§,"shootgun_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-EE§,"shootgun_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-I-§,"sniper_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-I-§,"sniper_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-I-§,"sniper_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-I-§,"sniper_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_Bomb1,"bomb_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_Bomb1,"bomb_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_Bomb1,"bomb_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_Bomb1,"bomb_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-N9§,"bomb_shoot_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-N9§,"bomb_shoot_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-N9§,"bomb_shoot_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-N9§,"bomb_shoot_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-Aj§,"rocket_launch_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-Aj§,"rocket_launch_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-Aj§,"rocket_launch_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-Aj§,"rocket_launch_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-RV§,"bolt_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-RV§,"bolt_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-RV§,"bolt_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-RV§,"bolt_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-CU§,"bolt_sorcerer_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-CU§,"bolt_sorcerer_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-CU§,"bolt_sorcerer_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-CU§,"bolt_sorcerer_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-Io§,"ray_arcane_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-Io§,"ray_arcane_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-Io§,"ray_arcane_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-Io§,"ray_arcane_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-Pq§,"ray_arcane_desintegrate_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-Pq§,"ray_arcane_desintegrate_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-Pq§,"ray_arcane_desintegrate_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-Pq§,"ray_arcane_desintegrate_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-PE§,"ray_polymorph_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-PE§,"ray_polymorph_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-PE§,"ray_polymorph_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-PE§,"ray_polymorph_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyExplode1,"death_explode_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyExplode1,"death_explode_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyExplode1,"death_explode_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyExplode1,"death_explode_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-Jg§,"death_puff_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-Jg§,"death_puff_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-Jg§,"death_puff_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-Jg§,"death_puff_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-Qk§,"death_big_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-Qk§,"death_big_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-Qk§,"death_big_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead1,"death_human_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead2,"death_human_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead1,"death_human_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead3,"death_human_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead4,"death_human_pool_5");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead2,"death_human_pool_6");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead1,"death_human_pool_7");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead3,"death_human_pool_8");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead2,"death_human_pool_9");
         SoundManager.getInstance().addLibrarySound(Sound_HumanDead4,"death_human_pool_10");
         SoundManager.getInstance().addLibrarySound(§_-SM§,"death_skeleton_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-SM§,"death_skeleton_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-SM§,"death_skeleton_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-SM§,"death_skeleton_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-4f§,"death_goblin_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-4f§,"death_goblin_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-4f§,"death_goblin_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-4f§,"death_goblin_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-8E§,"death_orc_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-8E§,"death_orc_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-8E§,"death_orc_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-8h§,"death_troll_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-8h§,"death_troll_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-8h§,"death_troll_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-8h§,"death_troll_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-H6§,"death_elemental_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-H6§,"death_elemental_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-H6§,"death_elemental_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-3R§,"teleporth_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-3R§,"teleporth_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-3R§,"teleporth_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-3R§,"teleporth_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-FL§,"thorn_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-FL§,"thorn_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-FL§,"thorn_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-FL§,"thorn_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-PI§,"paladin_heal_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-PI§,"paladin_heal_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-PI§,"paladin_heal_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-PI§,"paladin_heal_pool_4");
         SoundManager.getInstance().addLibrarySound(§catch§,"shrapnel_pool_1");
         SoundManager.getInstance().addLibrarySound(§catch§,"shrapnel_pool_2");
         SoundManager.getInstance().addLibrarySound(§catch§,"shrapnel_pool_3");
         SoundManager.getInstance().addLibrarySound(§catch§,"shrapnel_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-3T§,"area_attack_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-3T§,"area_attack_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-3T§,"area_attack_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-3T§,"area_attack_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-17§,"enemy_healing_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-17§,"enemy_healing_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-17§,"enemy_healing_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-17§,"enemy_healing_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyRocketeer,"rocketeer_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyRocketeer,"rocketeer_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyRocketeer,"rocketeer_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_EnemyRocketeer,"rocketeer_pool_4");
         SoundManager.getInstance().addLibrarySound(Sound_Chieftain,"rage_pool_1");
         SoundManager.getInstance().addLibrarySound(Sound_Chieftain,"rage_pool_2");
         SoundManager.getInstance().addLibrarySound(Sound_Chieftain,"rage_pool_3");
         SoundManager.getInstance().addLibrarySound(Sound_Chieftain,"rage_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-3E§,"break_ice_pool_1");
         SoundManager.getInstance().addLibrarySound(§_-3E§,"break_ice_pool_2");
         SoundManager.getInstance().addLibrarySound(§_-3E§,"break_ice_pool_3");
         SoundManager.getInstance().addLibrarySound(§_-3E§,"break_ice_pool_4");
         SoundManager.getInstance().addLibrarySound(§_-En§,"hero_level_up");
         SoundManager.getInstance().addLibrarySound(Sound_HeroGerald1,"hero_gerald_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroGerald2,"hero_gerald_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroGerald3,"hero_gerald_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroGerald4,"hero_gerald_4");
         SoundManager.getInstance().addLibrarySound(§_-GE§,"hero_gerald_death");
         SoundManager.getInstance().addLibrarySound(§_-Jj§,"hero_gerald_deflect");
         SoundManager.getInstance().addLibrarySound(§_-KJ§,"hero_gerald_buff");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMalik1,"hero_malik_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMalik2,"hero_malik_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMalik3,"hero_malik_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMalik4,"hero_malik_4");
         SoundManager.getInstance().addLibrarySound(§_-Cb§,"hero_malik_death");
         SoundManager.getInstance().addLibrarySound(§_-5W§,"hero_malik_charge");
         SoundManager.getInstance().addLibrarySound(§_-Jv§,"hero_malik_hit");
         SoundManager.getInstance().addLibrarySound(§_-76§,"hero_malik_jump");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleria1,"hero_alleria_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleria2,"hero_alleria_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleria3,"hero_alleria_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleria4,"hero_alleria_4");
         SoundManager.getInstance().addLibrarySound(§_-6y§,"hero_alleria_death");
         SoundManager.getInstance().addLibrarySound(§_-Iz§,"hero_alleria_wildcat");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleriaSummon,"hero_alleria_summon");
         SoundManager.getInstance().addLibrarySound(Sound_HeroAlleriaMultishoot,"hero_alleria_multishoot");
         SoundManager.getInstance().addLibrarySound(Sound_HeroBolin1,"hero_bolin_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroBolin2,"hero_bolin_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroBolin3,"hero_bolin_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroBolin4,"hero_bolin_4");
         SoundManager.getInstance().addLibrarySound(§_-1C§,"hero_bolin_death");
         SoundManager.getInstance().addLibrarySound(§_-JW§,"hero_bolin_brea_shoot");
         SoundManager.getInstance().addLibrarySound(§_-C3§,"hero_bolin_brea_hit");
         SoundManager.getInstance().addLibrarySound(§_-Sn§,"hero_bolin_mine");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMage1,"hero_mage_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMage2,"hero_mage_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMage3,"hero_mage_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroMage4,"hero_mage_4");
         SoundManager.getInstance().addLibrarySound(§_-9q§,"hero_mage_death");
         SoundManager.getInstance().addLibrarySound(§_-4m§,"hero_mage_rain_charge");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_1");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_2");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_3");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_4");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_5");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_6");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_7");
         SoundManager.getInstance().addLibrarySound(§_-90§,"hero_mage_rain_drop_8");
         SoundManager.getInstance().addLibrarySound(§_-JM§,"hero_mage_shadow");
         SoundManager.getInstance().addLibrarySound(Sound_HeroIgnus1,"hero_ignus_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroIgnus2,"hero_ignus_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroIgnus3,"hero_ignus_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroIgnus4,"hero_ignus_4");
         SoundManager.getInstance().addLibrarySound(§_-Q5§,"hero_ignus_death");
         SoundManager.getInstance().addLibrarySound(§_-OG§,"hero_ignus_area");
         SoundManager.getInstance().addLibrarySound(§_-Aa§,"hero_ignus_fire_start");
         SoundManager.getInstance().addLibrarySound(Sound_HeroIgnusEnd,"hero_ignus_fire_end");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenas1,"hero_denas_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenas2,"hero_denas_2");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenas3,"hero_denas_3");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenas4,"hero_denas_4");
         SoundManager.getInstance().addLibrarySound(§_-7V§,"hero_denas_death");
         SoundManager.getInstance().addLibrarySound(§_-BU§,"hero_denas_attack");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenasBuff1,"hero_denas_buff_1");
         SoundManager.getInstance().addLibrarySound(Sound_HeroDenasBuff3,"hero_denas_buff_2");
      }
      
      public function loadLangs() : void
      {
         Locale.setString("C_WAVE","cn"," 波");
         Locale.setString("C_SEC","cn"," 秒");
         Locale.setString("C_LIFE","cn","生命值");
         Locale.setString("C_HEALING","cn","治疗");
         Locale.setString("C_RESPAWN","cn","重生");
         Locale.setString("C_ARMOR","cn","物理装甲");
         Locale.setString("C_RANGE","cn","范围");
         Locale.setString("C_DAMAGE","cn","伤害");
         Locale.setString("C_RELOAD","cn","攻击间隔");
         Locale.setString("C_COOLDOWN","cn","冷却时间");
         Locale.setString("C_UNLOCKS","cn","解开");
         Locale.setString("C_CURSE","cn","诅咒");
         Locale.setString("C_DURATION","cn","持续时间");
         Locale.setString("C_CHANCE","cn","机会");
         Locale.setString("C_SLOW","cn","慢");
         Locale.setString("C_ONSET_LIFE","cn","感染者");
         Locale.setString("C_MAX_ENEMIES","cn","最大敌军");
         Locale.setString("C_OVER_DURATION","cn"," / 秒");
         Locale.setString("C_ARMOR_0","cn","无");
         Locale.setString("C_ARMOR_1","cn","初级");
         Locale.setString("C_ARMOR_2","cn","中级");
         Locale.setString("C_ARMOR_3","cn","高级");
         Locale.setString("C_ARMOR_4","cn","特级");
         Locale.setString("C_SPEED_0","cn","慢");
         Locale.setString("C_SPEED_1","cn","中");
         Locale.setString("C_SPEED_2","cn","快");
         Locale.setString("C_RELOAD_0","cn","较长");
         Locale.setString("C_RELOAD_1","cn","长");
         Locale.setString("C_RELOAD_2","cn","普通");
         Locale.setString("C_RELOAD_3","cn","短");
         Locale.setString("C_RELOAD_4","cn","很短");
         Locale.setString("C_RANGE_0","cn","短");
         Locale.setString("C_RANGE_1","cn","中");
         Locale.setString("C_RANGE_2","cn","长");
         Locale.setString("C_RANGE_3","cn","较长");
         Locale.setString("C_RANGE_4","cn","超长");
         Locale.setString("C_UNKNOWN","cn","未知");
         Locale.setString("C_IRON_WAVE","cn","铁血攻势");
         Locale.setString("C_MODE_0","cn","战役模式");
         Locale.setString("C_MODE_1","cn","英雄模式");
         Locale.setString("C_MODE_2","cn","铁血模式");
         Locale.setString("C_DIFFICULTY_NORMAL","cn","完成普通难度");
         Locale.setString("C_DIFFICULTY_EASY","cn","完成简单难度");
         Locale.setString("C_DIFFICULTY_HARD","cn","完成困难难度");
         Locale.setString("TOWER_LOCKED_NAME","cn","尚未开启！");
         Locale.setString("TOWER_LOCKED_DESCRIPTION","cn","这个项目禁止使用。");
         Locale.setString("TOWER_BARRACKS_RALLY_POINT","cn","集结点");
         Locale.setString("TOWER_BARRACKS_RALLY_POINT_DESCRIPTION","cn","可以更换士兵们防守的集结点。");
         Locale.setString("TOWER_BARRACKS_NAME","cn","军营");
         Locale.setString("TOWER_BARRACKS_DESCRIPTION","cn","训练民兵成为坚强的战士来阻挡并伤害敌人。");
         Locale.setString("TOWER_BARRACKS_UPGRADE_LEVEL2_NAME","cn","步兵营队");
         Locale.setString("TOWER_BARRACKS_UPGRADE_LEVEL2_DESCRIPTION","cn","步兵有比民兵更好的训练与装备，是部队的中流砥柱。");
         Locale.setString("TOWER_BARRACKS_UPGRADE_LEVEL3_NAME","cn","骑士碉堡");
         Locale.setString("TOWER_BARRACKS_UPGRADE_LEVEL3_DESCRIPTION","cn","骑士是向国王宣示效忠的重装士兵。他们将阻挡敌人使其无法越雷池一步。");
         Locale.setString("TOWER_BARBARIANS_NAME","cn","蛮族部落");
         Locale.setString("TOWER_BARBARIANS_DESCRIPTION","cn","野蛮人是战场上的凶神恶煞，不过通常是以自己的生命为代价...。");
         Locale.setString("TOWER_BARBARIANS_SPECIAL","cn","大斧投掷，多斧流，猎捕之网");
         Locale.setString("TOWER_BARBARIANS_BLOODLUST_NAME","cn","狂战士之血");
         Locale.setString("TOWER_BARBARIANS_BLOODLUST_DESCRIPTION","cn","野蛮人受伤时会进入狂战士模式，每次攻击将再额外对敌人造成伤害。");
         Locale.setString("TOWER_BARBARIANS_BLOODLUST_NOTE","cn","让我生气你\n会后悔的！");
         Locale.setString("TOWER_BARBARIANS_THROWING_AXES_NAME","cn","大斧投掷");
         Locale.setString("TOWER_BARBARIANS_THROWING_AXES_DESCRIPTION","cn","野蛮人可以对一定范围内的地面或飞行敌人投掷大斧进行攻击。");
         Locale.setString("TOWER_BARBARIANS_THROWING_AXES_NOTE","cn","愿大斧能将敌人一斧两断！");
         Locale.setString("TOWER_BARBARIANS_DOUBLE_AXE_NAME","cn","多斧流");
         Locale.setString("TOWER_BARBARIANS_DOUBLE_AXE_DESCRIPTION","cn","每多一把斧头，野蛮人就会增加攻击威力。");
         Locale.setString("TOWER_BARBARIANS_DOUBLE_AXE_NOTE","cn","斧头加倍，欢乐加倍！");
         Locale.setString("TOWER_BARBARIANS_HUNTER_NETS_NAME","cn","猎捕之网");
         Locale.setString("TOWER_BARBARIANS_HUNTER_NETS_DESCRIPTION","cn","野蛮人是天生的猎人，他们可以丢出网子来暂时减缓飞行敌人的速度。");
         Locale.setString("TOWER_BARBARIANS_HUNTER_NETS_NOTE","cn","别跑！");
         Locale.setString("TOWER_PALADINS_NAME","cn","圣殿");
         Locale.setString("TOWER_PALADINS_DESCRIPTION","cn","圣骑士是神圣的战士，也是圣域与神明的守护者。");
         Locale.setString("TOWER_PALADINS_SPECIAL","cn","治疗之光，神圣攻击，勇气之盾");
         Locale.setString("TOWER_PALADINS_HEALING_NAME","cn","治疗之光");
         Locale.setString("TOWER_PALADINS_HEALING_DESCRIPTION","cn","圣骑士可以用神圣的光芒治疗他们的伤口。");
         Locale.setString("TOWER_PALADINS_HEALING_NOTE","cn","就是那个光！");
         Locale.setString("TOWER_PALADINS_HOLY_STRIKE_NAME","cn","神圣攻击");
         Locale.setString("TOWER_PALADINS_HOLY_STRIKE_DESCRIPTION","cn","每次攻击有一定机会变为神圣攻击，对一定范围内的敌人造成伤害。");
         Locale.setString("TOWER_PALADINS_HOLY_STRIKE_NOTE","cn","以圣焰洗净罪业！");
         Locale.setString("TOWER_PALADINS_SHIELD_NAME","cn","勇气之盾");
         Locale.setString("TOWER_PALADINS_SHIELD_DESCRIPTION","cn","提升防御力，让圣骑士更加强悍。");
         Locale.setString("TOWER_PALADINS_SHIELD_NOTE","cn","不屈不挠！视死如归！");
         Locale.setString("TOWER_ARCHERS_NAME","cn","弓箭塔");
         Locale.setString("TOWER_ARCHERS_DESCRIPTION","cn","弓箭手可以从远处攻击敌人。");
         Locale.setString("TOWER_ARCHERS_UPGRADE_LEVEL2_NAME","cn","射手箭塔");
         Locale.setString("TOWER_ARCHERS_UPGRADE_LEVEL2_DESCRIPTION","cn","射手有更远的攻击距离，更高的攻击伤害。");
         Locale.setString("TOWER_ARCHERS_UPGRADE_LEVEL3_NAME","cn","狙击箭塔");
         Locale.setString("TOWER_ARCHERS_UPGRADE_LEVEL3_DESCRIPTION","cn","当成为了狙击手之后，攻击距离与伤害都会比其他任何弓箭手更为强大！");
         Locale.setString("TOWER_RANGERS_NAME","cn","游侠箭塔");
         Locale.setString("TOWER_RANGERS_DESCRIPTION","cn","游侠是传说的弓箭大师，他们可以射的比任何人更快而且更远！");
         Locale.setString("TOWER_RANGERS_SPECIAL","cn","毒箭，森林之怒");
         Locale.setString("TOWER_RANGERS_POISON_NAME","cn","毒箭");
         Locale.setString("TOWER_RANGERS_POISON_DESCRIPTION","cn","中毒的敌人会随着时间经过累积伤害。");
         Locale.setString("TOWER_RANGERS_POISON_NOTE","cn","很快就不会痛了...。");
         Locale.setString("TOWER_RANGERS_THORNS_NAME","cn","森林之怒");
         Locale.setString("TOWER_RANGERS_THORNS_DESCRIPTION","cn","召唤藤蔓与荆棘制造陷阱，困住范围内的地面敌人。");
         Locale.setString("TOWER_RANGERS_THORNS_NOTE","cn","中计了吧！");
         Locale.setString("TOWER_MUSKETEERS_NAME","cn","火枪要塞");
         Locale.setString("TOWER_MUSKETEERS_DESCRIPTION","cn","耐心、细心、和精准的射击技术，再搭配上先进的武器后就成了最强悍的狙击手。");
         Locale.setString("TOWER_MUSKETEERS_SPECIAL","cn","狙击，散弹鎗");
         Locale.setString("TOWER_MUSKETEERS_SNIPER_NAME","cn","狙击");
         Locale.setString("TOWER_MUSKETEERS_SNIPER_DESCRIPTION","cn","长距离狙击有机会对敌人一击必杀或是造成重大的伤害。");
         Locale.setString("TOWER_MUSKETEERS_SNIPER_NOTE","cn","来一个杀一个。");
         Locale.setString("TOWER_MUSKETEERS_SHRAPNEL_NAME","cn","散弹鎗");
         Locale.setString("TOWER_MUSKETEERS_SHRAPNEL_DESCRIPTION","cn","特别的爆炸弹药，炸开的弹片会对范围内所有地面敌人造成伤害。");
         Locale.setString("TOWER_MUSKETEERS_SHRAPNEL_NOTE","cn","吃我一发散弹吧！");
         Locale.setString("TOWER_ENGINEERS_NAME","cn","矮人炮塔");
         Locale.setString("TOWER_ENGINEERS_DESCRIPTION","cn","矮人炮塔可以对地面敌人造成范围伤害。");
         Locale.setString("TOWER_ENGINEERS_UPGRADE_LEVEL2_NAME","cn","矮人火炮");
         Locale.setString("TOWER_ENGINEERS_UPGRADE_LEVEL2_DESCRIPTION","cn","强化的矮人武器，可以对更大范围的敌人造成范围伤害。");
         Locale.setString("TOWER_ENGINEERS_UPGRADE_LEVEL3_NAME","cn","矮人榴炮");
         Locale.setString("TOWER_ENGINEERS_UPGRADE_LEVEL3_DESCRIPTION","cn","炮塔看起来越盖越大了，对吧？将没有敌人能承受这个破坏力。");
         Locale.setString("TOWER_BFG_NAME","cn","500mm巨炮");
         Locale.setString("TOWER_BFG_DESCRIPTION","cn","500mm攻城炮又名「巨炮」，是最大最凶恶的火炮之一。");
         Locale.setString("TOWER_BFG_SPECIAL","cn","龙息导弹，范围轰炸");
         Locale.setString("TOWER_BFG_MISSILE_NAME","cn","龙息导弹");
         Locale.setString("TOWER_BFG_MISSILE_DESCRIPTION","cn","龙息导弹绝不会失误，就算目标消失了它还是可以马上瞄准另一个目标进行攻击。");
         Locale.setString("TOWER_BFG_MISSILE_NOTE","cn","保证重伤，小心使用！");
         Locale.setString("TOWER_BFG_CLUSTER_NAME","cn","范围轰炸");
         Locale.setString("TOWER_BFG_CLUSTER_DESCRIPTION","cn","发射会在半空中四散的特制炸弹来进行广范围的轰炸。");
         Locale.setString("TOWER_BFG_CLUSTER_NOTE","cn","我喜欢清晨汽油弹闻起来的气味…");
         Locale.setString("C_BOMBS","cn","炸弹");
         Locale.setString("TOWER_TESLA_NAME","cn","特斯拉 x104");
         Locale.setString("TOWER_TESLA_DESCRIPTION","cn","矮人做出了拥有数千雷暴威力的强大武器，谁将成为它的受害者呢？");
         Locale.setString("TOWER_TESLA_SPECIAL","cn","连锁电击，充电过度");
         Locale.setString("TOWER_TESLA_CHARGED_BOLT_NAME","cn","连锁电击");
         Locale.setString("TOWER_TESLA_CHARGED_BOLT_DESCRIPTION","cn","连锁电击将会再额外攻击其他的目标。");
         Locale.setString("TOWER_TESLA_CHARGED_BOLT_NOTE","cn","电死你这个小王八蛋！");
         Locale.setString("TOWER_TESLA_OVERCHARGE_NAME","cn","充电过度");
         Locale.setString("TOWER_TESLA_OVERCHARGE_DESCRIPTION","cn","充电过度会在周围形成电场攻击范围内的敌人。");
         Locale.setString("TOWER_TESLA_OVERCHARGE_NOTE","cn","电闪雷击！");
         Locale.setString("TOWER_MAGES_NAME","cn","魔法之塔");
         Locale.setString("TOWER_MAGES_DESCRIPTION","cn","法师的魔法刺穿敌人的铠甲。");
         Locale.setString("TOWER_MAGES_UPGRADE_LEVEL2_NAME","cn","术士之塔");
         Locale.setString("TOWER_MAGES_UPGRADE_LEVEL2_DESCRIPTION","cn","术士的魔法撕裂敌人的身形。");
         Locale.setString("TOWER_MAGES_UPGRADE_LEVEL3_NAME","cn","巫师之塔");
         Locale.setString("TOWER_MAGES_UPGRADE_LEVEL3_DESCRIPTION","cn","巫师的魔法消灭敌军的存在。");
         Locale.setString("TOWER_ARCANE_NAME","cn","秘术之塔");
         Locale.setString("TOWER_ARCANE_DESCRIPTION","cn","秘术巫师研究如何改变现实，并致力于找出最致命的魔法。");
         Locale.setString("TOWER_ARCANE_SPECIAL","cn","死亡射线，传送术");
         Locale.setString("TOWER_ARCANE_TELEPORT_NAME","cn","传送术");
         Locale.setString("TOWER_ARCANE_TELEPORT_DESCRIPTION","cn","将一群敌人随机传送回已经经过的路上。");
         Locale.setString("TOWER_ARCANE_TELEPORT_NOTE","cn","只有凡人才会被空间所骗");
         Locale.setString("TOWER_ARCANE_DESINTEGRATE_NAME","cn","死亡射线");
         Locale.setString("TOWER_ARCANE_DESINTEGRATE_DESCRIPTION","cn","将敌军化为尘土，保证有效！");
         Locale.setString("TOWER_ARCANE_DESINTEGRATE_NOTE","cn","急急如律令");
         Locale.setString("TOWER_SORCERER_NAME","cn","魔导之塔");
         Locale.setString("TOWER_SORCERER_DESCRIPTION","cn","魔导士拥有近似黑暗的力量，可以一边伤害敌人一边削减敌人的装甲防御！");
         Locale.setString("C_CURSE_PRE","cn","敌人铠甲防御能力减半，维持五秒。");
         Locale.setString("TOWER_SORCERER_SPECIAL","cn","召唤元素，变羊术");
         Locale.setString("TOWER_SORCERER_POLIMORPH_NAME","cn","变羊术");
         Locale.setString("TOWER_SORCERER_POLIMORPH_DESCRIPTION","cn","将敌人变成无害的绵羊。绵羊没有铠甲、没有能力，但也不能阻挡。");
         Locale.setString("TOWER_SORCERER_POLIMORPH_NOTE","cn","咩~~~");
         Locale.setString("TOWER_SORCERER_ELEMENTAL_NAME","cn","召唤元素");
         Locale.setString("TOWER_SORCERER_ELEMENTAL_DESCRIPTION","cn","召唤拥有大地之力的岩石元素！它将攻击所有接近的敌人。");
         Locale.setString("TOWER_SORCERER_ELEMENTAL_NOTE","cn","大地是永恒不变的。");
         Locale.setString("TOWER_SELL","cn","售出");
         Locale.setString("TOWER_SELL_DESCRIPTION","cn","将塔售出并获得" + "{price}" + "金币");
         Locale.setString("POWER_FIREBALL_NAME","cn","陨石风暴");
         Locale.setString("POWER_FIREBALL_DESCRIPTION","cn","召唤燃烧的陨石从天而降。");
         Locale.setString("POWER_REINFORCEMENTS_NAME","cn","呼叫援军");
         Locale.setString("POWER_REINFORCEMENTS_DESCRIPTION","cn","召唤援军前来与敌人战斗。");
         Locale.setString("POWER_LIGHTNING_NAME","cn","雷击");
         Locale.setString("POWER_LIGHTNING_DESCRIPTION","cn","对一名敌人使用雷击魔法。");
         Locale.setString("SOLDIER_STANDARD_1_NAME","cn","士兵");
         Locale.setString("SOLDIER_STANDARD_2_NAME","cn","士兵");
         Locale.setString("SOLDIER_STANDARD_3_NAME","cn","士兵");
         Locale.setString("SOLDIER_PALADIN_NAME","cn","圣骑士");
         Locale.setString("SOLDIER_BARBARIAN_NAME","cn","野蛮人");
         Locale.setString("SOLDIER_ELEMENTAL_NAME","cn","元素");
         Locale.setString("SOLDIER_FARMER_PAUL_NAME","cn","民兵");
         Locale.setString("SOLDIER_FARMER_JOHN_NAME","cn","民兵");
         Locale.setString("SOLDIER_FARMER_RINGO_NAME","cn","民兵");
         Locale.setString("SOLDIER_MILITIA_NAME","cn","义勇军");
         Locale.setString("SOLDIER_WARRIOR_NAME","cn","战士");
         Locale.setString("SOLDIER_KNIGHT_NAME","cn","骑士");
         Locale.setString("SOLDIER_SASQUASH_NAME","cn","萨克斯奇");
         Locale.setString("SOLDIER_RANDOM_1_NAME","cn","陆飞");
         Locale.setString("SOLDIER_RANDOM_2_NAME","cn","琢洛");
         Locale.setString("SOLDIER_RANDOM_3_NAME","cn","山制");
         Locale.setString("SOLDIER_RANDOM_4_NAME","cn","乔拔");
         Locale.setString("SOLDIER_RANDOM_5_NAME","cn","卜鲁克");
         Locale.setString("SOLDIER_RANDOM_6_NAME","cn","罗苹");
         Locale.setString("SOLDIER_RANDOM_7_NAME","cn","乌索布");
         Locale.setString("SOLDIER_RANDOM_8_NAME","cn","那美");
         Locale.setString("SOLDIER_RANDOM_9_NAME","cn","佛朗奇");
         Locale.setString("SOLDIER_RANDOM_10_NAME","cn","陆飞");
         Locale.setString("SOLDIER_RANDOM_11_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_12_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_13_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_14_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_15_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_16_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_17_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_18_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_19_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_20_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_21_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_22_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_23_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_24_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_25_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_26_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_27_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_28_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_29_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_30_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_31_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_32_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_33_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_34_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_35_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_36_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_37_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_38_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_39_NAME","cn","");
         Locale.setString("SOLDIER_RANDOM_40_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_1_NAME","cn","犀利哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_2_NAME","cn","鱿鱼哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_3_NAME","cn","励志哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_4_NAME","cn","装醒哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_5_NAME","cn","酱油哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_6_NAME","cn","东栀子");
         Locale.setString("SOLDIER_PALADIN_RANDOM_7_NAME","cn","春哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_8_NAME","cn","火雷锋");
         Locale.setString("SOLDIER_PALADIN_RANDOM_9_NAME","cn","给力哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_10_NAME","cn","犀利哥");
         Locale.setString("SOLDIER_PALADIN_RANDOM_11_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_12_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_13_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_14_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_15_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_16_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_17_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_18_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_19_NAME","cn","");
         Locale.setString("SOLDIER_PALADIN_RANDOM_20_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_1_NAME","cn","高富帅");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_2_NAME","cn","屌丝");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_3_NAME","cn","凤凰男");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_4_NAME","cn","黑木耳");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_5_NAME","cn","白富美");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_6_NAME","cn","麦霸 ");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_7_NAME","cn","贰货");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_8_NAME","cn","土肥圆");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_9_NAME","cn","熊孩子");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_10_NAME","cn","高富帅");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_11_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_12_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_13_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_14_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_15_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_16_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_17_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_18_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_19_NAME","cn","");
         Locale.setString("SOLDIER_BARBARIAN_RANDOM_20_NAME","cn","");
         Locale.setString("SOLDIER_ELVES_RANDOM_1_NAME","cn","爱利隆");
         Locale.setString("SOLDIER_ELVES_RANDOM_2_NAME","cn","热狗拉斯");
         Locale.setString("SOLDIER_ELVES_RANDOM_3_NAME","cn","艾尔拉顿");
         Locale.setString("SOLDIER_ELVES_RANDOM_4_NAME","cn","芬葛林");
         Locale.setString("SOLDIER_ELVES_RANDOM_5_NAME","cn","吉尔-阿拉德");
         Locale.setString("SOLDIER_ELVES_RANDOM_6_NAME","cn","芬威尔");
         Locale.setString("SOLDIER_ELVES_RANDOM_7_NAME","cn","爱文");
         Locale.setString("SOLDIER_ELVES_RANDOM_8_NAME","cn","席威世");
         Locale.setString("SOLDIER_ELVES_RANDOM_9_NAME","cn","艾卢尼");
         Locale.setString("SOLDIER_ELVES_RANDOM_10_NAME","cn","爱利隆");
         Locale.setString("SOLDIER_PREMIUM_DARTH_VADER_1_NAME","cn","黑色头盔");
         Locale.setString("SOLDIER_PREMIUM_DARTH_VADER_2_NAME","cn","黑暗侵略者");
         Locale.setString("SOLDIER_PREMIUM_DARTH_VADER_3_NAME","cn","飞镖闪躲者");
         Locale.setString("SOLDIER_PREMIUM_OBI_WAN_1_NAME","cn","欧比旺");
         Locale.setString("SOLDIER_PREMIUM_OBI_WAN_2_NAME","cn","伊旺‧肯诺比");
         Locale.setString("SOLDIER_PREMIUM_OBI_WAN_3_NAME","cn","亚历‧肯诺比");
         Locale.setString("SOLDIER_PREMIUM_YODA_1_NAME","cn","优达");
         Locale.setString("SOLDIER_PREMIUM_YODA_2_NAME","cn","优格");
         Locale.setString("SOLDIER_PREMIUM_YODA_3_NAME","cn","鬼灵精");
         Locale.setString("SOLDIER_PREMIUM_CHEWAKA_1_NAME","cn","洽巴坎");
         Locale.setString("SOLDIER_PREMIUM_CHEWAKA_2_NAME","cn","洽卡哇卡");
         Locale.setString("SOLDIER_PREMIUM_CHEWAKA_3_NAME","cn","吉娃娃");
         Locale.setString("SOLDIER_PREMIUM_KEN_1_NAME","cn","肯尼");
         Locale.setString("SOLDIER_PREMIUM_KEN_2_NAME","cn","基努");
         Locale.setString("SOLDIER_PREMIUM_KEN_3_NAME","cn","梅尔");
         Locale.setString("SOLDIER_PREMIUM_RYU_1_NAME","cn","流");
         Locale.setString("SOLDIER_PREMIUM_RYU_2_NAME","cn","席格");
         Locale.setString("SOLDIER_PREMIUM_RYU_3_NAME","cn","克劳德");
         Locale.setString("SOLDIER_PREMIUM_BLANKA_1_NAME","cn","白蓝");
         Locale.setString("SOLDIER_PREMIUM_BLANKA_2_NAME","cn","佛陀");
         Locale.setString("SOLDIER_PREMIUM_BLANKA_3_NAME","cn","怀特尼");
         Locale.setString("SOLDIER_PREMIUM_GUILLE_1_NAME","cn","凯尔");
         Locale.setString("SOLDIER_PREMIUM_GUILLE_2_NAME","cn","阿力固");
         Locale.setString("SOLDIER_PREMIUM_GUILLE_3_NAME","cn","长官");
         Locale.setString("SOLDIER_PREMIUM_LIU_KANG_1_NAME","cn","路易康");
         Locale.setString("SOLDIER_PREMIUM_LIU_KANG_2_NAME","cn","杰基");
         Locale.setString("SOLDIER_PREMIUM_LIU_KANG_3_NAME","cn","布鲁斯");
         Locale.setString("SOLDIER_PREMIUM_SCORPION_1_NAME","cn","毒蝎");
         Locale.setString("SOLDIER_PREMIUM_SCORPION_2_NAME","cn","泰迪欧斯");
         Locale.setString("SOLDIER_PREMIUM_SCORPION_3_NAME","cn","啦啦啦");
         Locale.setString("SOLDIER_PREMIUM_SUB_ZERO_1_NAME","cn","绝对七度");
         Locale.setString("SOLDIER_PREMIUM_SUB_ZERO_2_NAME","cn","绝对三度");
         Locale.setString("SOLDIER_PREMIUM_SUB_ZERO_3_NAME","cn","绝对五度");
         Locale.setString("SOLDIER_PREMIUM_GORO_1_NAME","cn","波郎");
         Locale.setString("SOLDIER_PREMIUM_GORO_2_NAME","cn","多郎");
         Locale.setString("SOLDIER_PREMIUM_GORO_3_NAME","cn","杀手太郎");
         Locale.setString("ENEMY_SHEEP_NAME","cn","绵羊");
         Locale.setString("ENEMY_GOBLIN_NAME","cn","哥布林");
         Locale.setString("ENEMY_GOBLIN_DESCRIPTION","cn","小型而没有出色能力的类人型生物。");
         Locale.setString("ENEMY_FAT_ORC_NAME","cn","兽人");
         Locale.setString("ENEMY_FAT_ORC_DESCRIPTION","cn","穿着轻型装甲的强壮野人。");
         Locale.setString("ENEMY_OGRE_NAME","cn","食人魔");
         Locale.setString("ENEMY_OGRE_DESCRIPTION","cn","巨大、粗暴又强壮的类人生物，他们所经之处将尽为废墟。");
         Locale.setString("ENEMY_SHAMAN_NAME","cn","萨满");
         Locale.setString("ENEMY_SHAMAN_DESCRIPTION","cn","部落的巫医，拥有魔法抗性。");
         Locale.setString("ENEMY_SHAMAN_SPECIAL","cn","*治疗部队");
         Locale.setString("ENEMY_WULF_NAME","cn","恶狼");
         Locale.setString("ENEMY_WULF_DESCRIPTION","cn","又快又凶恶的生物，可以闪避近战攻击。");
         Locale.setString("ENEMY_WULF_SPECIAL","cn","*可闪避近战攻击");
         Locale.setString("ENEMY_BANDIT_NAME","cn","强盗");
         Locale.setString("ENEMY_BANDIT_DESCRIPTION","cn","他们敏捷迅速，可以很快的消灭敌人。");
         Locale.setString("ENEMY_BANDIT_SPECIAL","cn","*可闪避近战攻击");
         Locale.setString("ENEMY_BRIGAND_NAME","cn","土匪");
         Locale.setString("ENEMY_BRIGAND_DESCRIPTION","cn","穿着铠甲的歹徒，可以承受大量伤害。");
         Locale.setString("ENEMY_MARAUDER_NAME","cn","掠夺者");
         Locale.setString("ENEMY_MARAUDER_DESCRIPTION","cn","穿着装甲、壮硕且训练有素的不法份子，通常是土匪与强盗的头头。");
         Locale.setString("ENEMY_WORG_NAME","cn","座狼");
         Locale.setString("ENEMY_WORG_DESCRIPTION","cn","敏捷又狡猾的野兽，可闪避近战攻击并抵御魔法。");
         Locale.setString("ENEMY_WORG_SPECIAL","cn","*可闪避近战攻击");
         Locale.setString("ENEMY_GARGOYLE_NAME","cn","石像怪");
         Locale.setString("ENEMY_GARGOYLE_DESCRIPTION","cn","恶劣的有翼怪物，可以飞行避开士兵与炮塔。");
         Locale.setString("ENEMY_GARGOYLE_SPECIAL","cn","*飞行");
         Locale.setString("ENEMY_SPIDER_NAME","cn","蜘蛛女王");
         Locale.setString("ENEMY_SPIDER_DESCRIPTION","cn","拥有强大魔法抗性的野兽，会产下含有好几只幼虫的卵。");
         Locale.setString("ENEMY_SPIDER_SPECIAL","cn","*产卵");
         Locale.setString("ENEMY_SPIDERSMALL_NAME","cn","大蜘蛛");
         Locale.setString("ENEMY_SPIDERSMALL_DESCRIPTION","cn","快速且拥有魔法抗性的凶恶敌人。");
         Locale.setString("ENEMY_SPIDERTINY_NAME","cn","蜘蛛幼虫");
         Locale.setString("ENEMY_SPIDERTINY_DESCRIPTION","cn","非常弱的蜘蛛幼虫");
         Locale.setString("ENEMY_DARK_NIGHT_NAME","cn","黑暗骑士");
         Locale.setString("ENEMY_DARK_NIGHT_DESCRIPTION","cn","重装的堕落骑士，几乎不会受到物理伤害。");
         Locale.setString("ENEMY_SHADOW_ARCHER_NAME","cn","幽影射手");
         Locale.setString("ENEMY_SHADOW_ARCHER_DESCRIPTION","cn","致命的射手，会射击周遭的士兵。");
         Locale.setString("ENEMY_SHADOW_ARCHER_SPECIAL","cn","*射箭");
         Locale.setString("ENEMY_GOLEM_HEAD_NAME","cn","魔像头颅");
         Locale.setString("ENEMY_GOLEM_HEAD_DESCRIPTION","cn","神奇的黑暗魔法机器。");
         Locale.setString("ENEMY_JUGGERNAUT_NAME","cn","狂暴魔像");
         Locale.setString("ENEMY_JUGGERNAUT_DESCRIPTION","cn","一个无法停止的疯狂机器，将抹杀所有试图阻止它的军队。");
         Locale.setString("ENEMY_JUGGERNAUT_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_WHITE_WOLF_NAME","cn","白狼");
         Locale.setString("ENEMY_WHITE_WOLF_DESCRIPTION","cn","狡猾而致命的野兽。除了最好的战士外，牠们几乎可以战胜一切。");
         Locale.setString("ENEMY_WHITE_WOLF_SPECIAL","cn","*可闪避近战攻击");
         Locale.setString("ENEMY_TROLL_NAME","cn","巨魔");
         Locale.setString("ENEMY_TROLL_DESCRIPTION","cn","非常强壮的战士，受到的伤会迅速痊愈。");
         Locale.setString("ENEMY_TROLL_SPECIAL","cn","*痊愈");
         Locale.setString("ENEMY_TROLL_CHIEFTAIN_NAME","cn","巨魔酋长");
         Locale.setString("ENEMY_TROLL_CHIEFTAIN_DESCRIPTION","cn","巨魔酋长会激励属下，藉以提升他们的攻击伤害、铠甲等级、速度与生命值。");
         Locale.setString("ENEMY_TROLL_CHIEFTAIN_SPECIAL","cn","*痊愈，激励盟友");
         Locale.setString("ENEMY_TROLL_AXE_THROWER_NAME","cn","巨魔冠军");
         Locale.setString("ENEMY_TROLL_AXE_THROWER_DESCRIPTION","cn","巨魔冠军会凶恶的投掷斧头攻击，是部落的菁英战士。");
         Locale.setString("ENEMY_TROLL_AXE_THROWER_SPECIAL","cn","*痊愈、投掷破甲斧");
         Locale.setString("ENEMY_YETI_NAME","cn","雪怪");
         Locale.setString("ENEMY_YETI_DESCRIPTION","cn","类人猿的大型生物，可以一击消灭众多士兵。");
         Locale.setString("ENEMY_YETI_SPECIAL","cn","*范围攻击");
         Locale.setString("ENEMY_YETI_GUARDIAN_NAME","cn","雪怪守卫");
         Locale.setString("ENEMY_YETI_GUARDIAN_DESCRIPTION","cn","雪怪守卫");
         Locale.setString("ENEMY_YETI_BOSS_NAME","cn","大雪怪");
         Locale.setString("ENEMY_YETI_BOSS_DESCRIPTION","cn","只存在于冰天雪地的世界尽头，传说中的凶恶生物。");
         Locale.setString("ENEMY_YETI_BOSS_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_SLAYER_NAME","cn","黑暗杀手");
         Locale.setString("ENEMY_SLAYER_DESCRIPTION","cn","源于黑暗，阻挡他的下场只有死路一条。");
         Locale.setString("ENEMY_ROCKETEER_NAME","cn","火箭骑士");
         Locale.setString("ENEMY_ROCKETEER_DESCRIPTION","cn","半人半机械的火箭骑士，跟随黑暗领主征讨天涯海角。");
         Locale.setString("ENEMY_ROCKETEER_SPECIAL","cn","*飞行，加速");
         Locale.setString("ENEMY_SKELETON_NAME","cn","骷髅");
         Locale.setString("ENEMY_SKELETON_DESCRIPTION","cn","只遵从邪灵的命令，毫无意识的傀儡。");
         Locale.setString("ENEMY_SKELETON_SPECIAL","cn","");
         Locale.setString("ENEMY_SKELETON_BIG_NAME","cn","骷髅骑士");
         Locale.setString("ENEMY_SKELETON_BIG_DESCRIPTION","cn","骷髅骑士是伟大战士们死后被诅咒而成的。");
         Locale.setString("ENEMY_SKELETON_BIG_SPECIAL","cn","");
         Locale.setString("ENEMY_DEMON_WOLF_NAME","cn","恶魔猎犬");
         Locale.setString("ENEMY_DEMON_WOLF_DESCRIPTION","cn","凶恶而可怕的生物，牠们是恶魔领主的忠心猎犬。");
         Locale.setString("ENEMY_DEMON_WOLF_SPECIAL","cn","*地狱烈火");
         Locale.setString("ENEMY_DEMON_NAME","cn","恶魔之子");
         Locale.setString("ENEMY_DEMON_DESCRIPTION","cn","恐怖的地狱生物，死亡后会发生爆炸伤害附近的士兵。");
         Locale.setString("ENEMY_DEMON_SPECIAL","cn","*地狱烈火");
         Locale.setString("ENEMY_DEMON_MAGE_NAME","cn","恶魔领主");
         Locale.setString("ENEMY_DEMON_MAGE_DESCRIPTION","cn","恶魔领主率领恶魔军团参加战斗，并用地狱之盾强化这些手下。");
         Locale.setString("ENEMY_DEMON_MAGE_SPECIAL","cn","*恶魔护盾，地狱烈火");
         Locale.setString("ENEMY_DEMON_IMP_NAME","cn","恶魔小鬼");
         Locale.setString("ENEMY_DEMON_IMP_DESCRIPTION","cn","地狱的捣蛋魔物，常常混在石像鬼的飞行队伍中。");
         Locale.setString("ENEMY_DEMON_IMP_SPECIAL","cn","*飞行");
         Locale.setString("ENEMY_NECROMANCER_NAME","cn","死灵法师");
         Locale.setString("ENEMY_NECROMANCER_DESCRIPTION","cn","死灵法师是黑暗艺术的大师，会召唤不死生物当他的爪牙。");
         Locale.setString("ENEMY_NECROMANCER_SPECIAL","cn","*骷髅召唤，远距攻击");
         Locale.setString("ENEMY_LAVA_ELEMENTAL_NAME","cn","熔岩元素");
         Locale.setString("ENEMY_LAVA_ELEMENTAL_DESCRIPTION","cn","熔岩元素以岩石和火焰构成，是代表死亡与毁灭的存在。");
         Locale.setString("ENEMY_LAVA_ELEMENTAL_SPECIAL","cn","*范围攻击");
         Locale.setString("ENEMY_VEZNAN_NAME","cn","恶魔巫师卫兹南");
         Locale.setString("ENEMY_VEZNAN_DESCRIPTION","cn","最邪恶的存在，要留意他的恶劣玩笑！");
         Locale.setString("ENEMY_VEZNAN_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_SARELGAZ_NAME","cn","蜘蛛女王萨雷格兹");
         Locale.setString("ENEMY_SARELGAZ_DESCRIPTION","cn","萨雷格兹是传说中的蜘蛛女王，统治着整个北方地区。");
         Locale.setString("ENEMY_SARELGAZ_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_SARELGAZ_SMALL_NAME","cn","蛛王之子");
         Locale.setString("ENEMY_SARELGAZ_SMALL_DESCRIPTION","cn","薩雷格茲的子嗣，是恐怖、致命又難纏的怪物。");
         Locale.setString("ENEMY_SARELGAZ_SMALL_SPECIAL","cn","*投掷炸弹");
         Locale.setString("ENEMY_GOBLIN_ZAPPER_NAME","cn","哥布林敢死队");
         Locale.setString("ENEMY_GOBLIN_ZAPPER_DESCRIPTION","cn","强化的无畏哥布林士兵，唯一任务就是将炸弹丢进敌军中心。");
         Locale.setString("ENEMY_GOBLIN_ZAPPER_SPECIAL","cn","*投掷炸弹");
         Locale.setString("ENEMY_FOREST_TROLL_NAME","cn","森林巨魔");
         Locale.setString("ENEMY_FOREST_TROLL_DESCRIPTION","cn","最大最难杀死的巨魔，这些庞然大物的伤口几乎可以立即复原。");
         Locale.setString("ENEMY_FOREST_TROLL_SPECIAL","cn","*痊愈，范围攻击");
         Locale.setString("ENEMY_ORC_WOLF_RIDER_NAME","cn","狼骑士");
         Locale.setString("ENEMY_ORC_WOLF_RIDER_DESCRIPTION","cn","骑乘在座狼上战斗的可怕敌人，当座狼死亡后他们会离开座骑继续战斗。");
         Locale.setString("ENEMY_ORC_WOLF_RIDER_SPECIAL","cn","*可以离开座骑战斗");
         Locale.setString("ENEMY_ORC_ARMORED_NAME","cn","兽人冠军");
         Locale.setString("ENEMY_ORC_ARMORED_DESCRIPTION","cn","兽人冠军是兽人部落的菁英部队，配有重型装甲。");
         Locale.setString("ENEMY_ORC_ARMORED_SPECIAL","cn","");
         Locale.setString("ENEMY_BOSS_GOBLIN_CHIEFTAIN_NAME","cn","兽人酋长古拉克");
         Locale.setString("ENEMY_BOSS_GOBLIN_CHIEFTAIN_DESCRIPTION","cn","兽人们又敬又怕的酋长。他的战斗实力只有他那无聊到不可思议的营火故事可以相比拟！");
         Locale.setString("ENEMY_BOSS_GOBLIN_CHIEFTAIN_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_THE_THING_NAME","cn","腐沼巨人");
         Locale.setString("ENEMY_THE_THING_DESCRIPTION","cn","从最恶毒、最腐败的地方诞生的大型植物魔物");
         Locale.setString("ENEMY_THE_THING_SPECIAL","cn","");
         Locale.setString("ENEMY_ZOMBIE_NAME","cn","腐植丧尸");
         Locale.setString("ENEMY_ZOMBIE_DESCRIPTION","cn","堕落的战士们。他们的身体被森林所寄宿，徒留农夫外貌的空壳。");
         Locale.setString("ENEMY_ZOMBIE_SPECIAL","cn","*痊愈，范围攻击");
         Locale.setString("ENEMY_ROTTEN_TREE_NAME","cn","腐化树妖");
         Locale.setString("ENEMY_ROTTEN_TREE_DESCRIPTION","cn","这些钢硬的树妖曾是森林的保护者。");
         Locale.setString("ENEMY_ROTTEN_TREE_SPECIAL","cn","*可以离开座骑战斗");
         Locale.setString("ENEMY_ROTTEN_SPIDER_NAME","cn","腐毒蜘蛛");
         Locale.setString("ENEMY_ROTTEN_SPIDER_DESCRIPTION","cn","好斗的掠食者，会产下变异蜘蛛来攻击牠们的猎物。");
         Locale.setString("ENEMY_ROTTEN_SPIDER_SPECIAL","cn","");
         Locale.setString("ENEMY_ROTTEN_TREE_BOSS_NAME","cn","腐森之心");
         Locale.setString("ENEMY_ROTTEN_TREE_BOSS_DESCRIPTION","cn","腐化森林的中心，也是这次腐败现象的源头。");
         Locale.setString("ENEMY_ROTTEN_TREE_BOSS_SPECIAL","cn","*头目");
         Locale.setString("ENEMY_RAIDER_NAME","cn","蛮族佣兵");
         Locale.setString("ENEMY_RAIDER_DESCRIPTION","cn","装备精良的贪婪佣兵，只为战利品与赏金而战。");
         Locale.setString("ENEMY_RAIDER_SPECIAL","cn","*远距离魔法攻击");
         Locale.setString("ENEMY_PILLAGER_NAME","cn","江洋大盗");
         Locale.setString("ENEMY_PILLAGER_DESCRIPTION","cn","魔法抗性极高的罪犯首领，会派遣拥有地狱之刃的部下进行攻击。");
         Locale.setString("ENEMY_PILLAGER_SPECIAL","cn","*范围魔法攻击");
         Locale.setString("ENEMY_BANDIT_BOSS_NAME","cn","金霸王");
         Locale.setString("ENEMY_BANDIT_BOSS_DESCRIPTION","cn","王国内最狡猾、最贪婪的掠夺者。别担心，你的黄金他也不会放过的！");
         Locale.setString("ENEMY_BANDIT_BOSS_SPECIAL","cn","*头目");
         Locale.setString("LEVEL_MODE_CAMPAIGN","cn","战役模式");
         Locale.setString("LEVEL_MODE_HEROIC","cn","英雄模式");
         Locale.setString("LEVEL_MODE_HEROIC_DESCRIPTION","cn","敌人的菁英部队将考验你的战术技巧！朝成为最英勇的防御者前进吧！");
         Locale.setString("LEVEL_MODE_IRON","cn","铁血模式");
         Locale.setString("LEVEL_MODE_IRON_DESCRIPTION","cn","铁血模式是对防御者的最终考验！挑战你的策略与技巧极限！");
         Locale.setString("LEVEL_1_TITLE","cn","南部港口");
         Locale.setString("LEVEL_1_HISTORY","cn","你好，英勇而荣耀的勇士！身为统领王国壮盛军容的一位将军，迪纳斯国王需要你的协助。\n\n南部港口近日传来数起拦路打截与非法份子出没的报告，你必须带领一支部队前往南部港口支持防御。\n\n祝武运昌隆！");
         Locale.setString("LEVEL_1_HEROIC","cn","");
         Locale.setString("LEVEL_1_IRON","cn","");
         Locale.setString("LEVEL_2_TITLE","cn","郊区农园");
         Locale.setString("LEVEL_2_HISTORY","cn","干的好！透过你迅速的调查指出，这并非单纯出没在南部港口的盗匪，而是哥布林与兽人们有组织的攻击。\n\n现在他们的前锋部队已经逐渐逼近港口北边的农村区域。\n\n我们必须赶在他们之前建立有效的防线！");
         Locale.setString("LEVEL_2_HEROIC","cn","");
         Locale.setString("LEVEL_2_IRON","cn","");
         Locale.setString("LEVEL_3_TITLE","cn","帕格拉斯");
         Locale.setString("LEVEL_3_HISTORY","cn","当你的部队还在沉浸在击退哥布林与兽人的喜悦时，我们收到了一则坏消息。\n\n帕格拉斯区域正遭受敌人以压倒性的兵力包围。\n\n这视同为对王国的公开宣战：将军，战争开始了！");
         Locale.setString("LEVEL_3_HEROIC","cn","");
         Locale.setString("LEVEL_3_IRON","cn","");
         Locale.setString("LEVEL_4_TITLE","cn","双子河畔");
         Locale.setString("LEVEL_4_HISTORY","cn","敌人的部队正从东方穿过石崖山脉而来，这代表战锤区域已经沦陷，而我们的首都也正处于危急当中。\n\n从侦查兵传回来的报告推断，阻止敌人前进的最佳场所将会是─双子河畔。");
         Locale.setString("LEVEL_4_HEROIC","cn","");
         Locale.setString("LEVEL_4_IRON","cn","");
         Locale.setString("LEVEL_5_TITLE","cn","银橡森林");
         Locale.setString("LEVEL_5_HISTORY","cn","在双子河畔成功阻止敌人的部队后几天，我们来到了银橡森林的前哨站…但此处士兵士气却异常低落。\n\n驻军最近已经遭受到了好几波攻击，而且侦查兵也传来报告指出有一波数量庞大的敌军正在接近此处。\n\n唯一的好消息是...游侠部队正在前来帮助我们的路上。");
         Locale.setString("LEVEL_5_HEROIC","cn","");
         Locale.setString("LEVEL_5_IRON","cn","");
         Locale.setString("LEVEL_6_TITLE","cn","城塞决战");
         Locale.setString("LEVEL_6_HISTORY","cn","在好几天的行军后，我们终于抵达了首都：利尼雷亚。\n\n决战的时刻即将到来，我们将在南门布阵迎击，绝不可让南门防线被突破！\n\n为了进一步提升战力，国王派遣了两个部队加入了阵营之中。秘术巫师将提供强大的伤害火力，而圣骑士会以他们的勇气激励你的部队。");
         Locale.setString("LEVEL_6_HEROIC","cn","");
         Locale.setString("LEVEL_6_IRON","cn","");
         Locale.setString("LEVEL_7_TITLE","cn","冰封矿山");
         Locale.setString("LEVEL_7_HISTORY","cn","首都安全了！谢谢你，将军！现在我们伟大的国王将派遣你一项重大的任务：建立一条可以安全穿越山脉的道路，以便进攻瓦拉杜区域并击败恶魔巫师卫兹南和他的部队。\n\n你的第一步必须先从夺回冰封矿山开始。冰封矿山已经废弃了许久，现在已经成了巨魔的巢穴。为了确保任务完成，自此开始皇家火枪部队将加入你的阵营。");
         Locale.setString("LEVEL_7_HEROIC","cn","");
         Locale.setString("LEVEL_7_IRON","cn","");
         Locale.setString("LEVEL_8_TITLE","cn","冰风之谷");
         Locale.setString("LEVEL_8_HISTORY","cn","冰风之谷是山脉中最寒冷的区域，但我们仍必须继续前进。\n\n部队已经被巨魔围攻了好几天，侦查兵也发现到敌军正在进行大规模的包围行动，其中还有一些比巨魔更疯狂的敌人…。\n\n如果我们要在这进行决战，那么这将是测试新的炮塔装备的最佳场所。此外，如果在此设置蛮族部落的话，我们将可以招募到更多样的部队。");
         Locale.setString("LEVEL_8_HEROIC","cn","");
         Locale.setString("LEVEL_8_IRON","cn","");
         Locale.setString("LEVEL_9_TITLE","cn","暴云寺院");
         Locale.setString("LEVEL_9_HISTORY","cn","抵达暴云寺院对我们来说再好也不过了，将军！\n\n暴云术士将会听从你的命令行动，而且将以咒语打开前往瓦拉杜的传送门。然而，我们必须在他们咒语完全完成之前协助他们做好防御。\n\n报告传来现在有些讨厌的东西正在接近，大家都开始屏息以待…。");
         Locale.setString("LEVEL_9_HEROIC","cn","");
         Locale.setString("LEVEL_9_IRON","cn","");
         Locale.setString("LEVEL_10_TITLE","cn","幽暗荒地");
         Locale.setString("LEVEL_10_HISTORY","cn","我们已经到达了恐怖的瓦拉杜。这是个可怜游魂在此四处飘荡的荒芜之地。\n\n向上帝祈祷吧，祈祷这地方不要把你的灵魂当成过路费夺走…。");
         Locale.setString("LEVEL_10_HEROIC","cn","");
         Locale.setString("LEVEL_10_IRON","cn","");
         Locale.setString("LEVEL_11_TITLE","cn","遗忘山谷");
         Locale.setString("LEVEL_11_HISTORY","cn","穿越遗忘山谷不是一个简单的任务！至此我们已经接近旅程的终点，虽然大家已满身疲倦，但眼神里仍然充满奋勇向前的荣耀光芒。\n\n虽然这是一个充斥着火焰与岩石巨人的地方…但提高警戒并别为此苦恼才是通过此处的唯一方针。");
         Locale.setString("LEVEL_11_HEROIC","cn","");
         Locale.setString("LEVEL_11_IRON","cn","");
         Locale.setString("LEVEL_12_TITLE","cn","暗黑之塔");
         Locale.setString("LEVEL_12_HISTORY","cn","我们的军队已经集结到恶魔巫师卫兹南的塔前，一切都该在此做个了结了！这将是保卫王国的最终决战！来到此处之前所踏出的每一步，都让我们无法回头。\n\n现在，将是展现勇气的时刻！");
         Locale.setString("LEVEL_12_HEROIC","cn","");
         Locale.setString("LEVEL_12_IRON","cn","");
         Locale.setString("LEVEL_13_TITLE","cn","萨雷格斯的巢穴");
         Locale.setString("LEVEL_13_HISTORY","cn","将军！我们需要你与你英勇部下的协助！恶魔巫师卫兹南就算死亡还是留下了大麻烦。当你在最终决战时，卫兹南暗中派遣了部下唤醒恐怖的蜘蛛女王：萨雷格兹。\n\n我们曾经以为蜘蛛女王将永远沉眠，但她终究是醒了过来。并且以强大的力量压倒了黑暗，控制了卫兹南的剩余部队。你必须击败他们，并且消灭萨雷格兹。");
         Locale.setString("LEVEL_13_HEROIC","cn","");
         Locale.setString("LEVEL_13_IRON","cn","");
         Locale.setString("LEVEL_14_TITLE","cn","阿卡洛斯的遗迹");
         Locale.setString("LEVEL_14_HISTORY","cn","虽然和平已经来临，但邪恶势力却仍蠢蠢欲动！我们的盟友传来了阿卡洛斯遗迹遭受兽人与哥布林大军所侵袭的报告。新任的兽人酋长：古拉克，在卫兹南死后趁机夺取了黑暗势力的领导权，并且率领军队攻击该区。\n\n你必须将这些侵略者驱逐出境！守护利尼雷亚的荣光！");
         Locale.setString("LEVEL_14_HEROIC","cn","");
         Locale.setString("LEVEL_14_IRON","cn","");
         Locale.setString("LEVEL_15_TITLE","cn","腐化森林");
         Locale.setString("LEVEL_15_HISTORY","cn","召唤你的军队吧！将军！黑暗之力正无情侵蚀我们敬爱的王国，我们必须立刻采取行动！根据报告指出，腐化森林已经完全被黑暗之力所「腐化」，并在森林深处打开了地狱的门扉。\n\n森林被死亡气息所笼罩，而且植物开始攻击所有接近它们的生物。你必须马上带领你的部队前往腐化森林找出问题的根源！");
         Locale.setString("LEVEL_15_HEROIC","cn","");
         Locale.setString("LEVEL_15_IRON","cn","");
         Locale.setString("LEVEL_16_TITLE","cn","寂静森林");
         Locale.setString("LEVEL_16_HISTORY","cn","将军！你必须再度集结你的部队，从敌人手中保护我们的王国。侦查兵发现到一群恶贯满盈的歹徒正聚集在寂静之森深处。这里是个一般民众不敢踏足之处…，然而你并不是一般民众。\n\n带领你的军队前往森林并击败这些歹徒，让他们后悔过去所犯下的一切。");
         Locale.setString("LEVEL_16_HEROIC","cn","Heroic Description 16");
         Locale.setString("LEVEL_16_IRON","cn","Iron Description 16");
         Locale.setString("LEVEL_17_TITLE","cn","盗贼老巢");
         Locale.setString("LEVEL_17_HISTORY","cn","干得好！你已经成功将这些卑鄙的歹徒击溃了！这次总攻击已经粉碎他们大部分的游荡势力，虽然仍有部分敌人逃入森林深处...。我们相信，这群非法份子在森林内有个藏有掠夺品的秘密基地是无庸置疑的！\n\n追击他们！将他们从巢穴中拖出来彻底击溃！并收回那些被盗走的物品。需要注意的是，这些不法份子很有可能正规划着狡猾的逃亡计划，请特别留意。");
         Locale.setString("LEVEL_17_HEROIC","cn","Heroic Description 17");
         Locale.setString("LEVEL_17_IRON","cn","Iron Description 17");
         Locale.setString("TIP_TITLE","cn","小技巧：");
         Locale.setString("TIP_1","cn","穿着铠甲的敌人与士兵会受到较少的物理伤害。");
         Locale.setString("TIP_2","cn","让多个防御塔搭配军营来对敌人集中攻击。");
         Locale.setString("TIP_3","cn","呼叫援军是一个分散敌人的好方法。");
         Locale.setString("TIP_4","cn","敌人越集中，炮塔的攻击越有效。");
         Locale.setString("TIP_5","cn","炮塔的伤害值在爆炸中心最高，然后向外递减。");
         Locale.setString("TIP_6","cn","经常呼叫援军来伤害并减缓敌人的前进速度。");
         Locale.setString("TIP_7","cn","陨石风暴最好瞄准在敌人前方一小段距离。");
         Locale.setString("TIP_8","cn","升级资源回收技能后，弓箭塔售出将只损失10%金币。");
         Locale.setString("TIP_9","cn","魔法是对付穿着铠甲敌人的最佳攻击方式。");
         Locale.setString("TIP_10","cn","飞行的敌人无法被士兵阻挡，而且大部分的炮塔也无法瞄准攻击他们。");
         Locale.setString("TIP_11","cn","拥有魔法抗性的敌人会受到较少的魔法伤害。");
         Locale.setString("TIP_12","cn","调整士兵的集结点，来创造更棒的策略！");
         Locale.setString("TIP_13","cn","有时建造大量的防御塔比集中升级少数的塔更有用！");
         Locale.setString("TIP_14","cn","铠甲无法减少中毒伤害。");
         Locale.setString("TIP_15","cn","尽快升级军营来训练新的士兵。");
         Locale.setString("TIP_16","cn","提早迎击下一波敌人可以获得金币奖励并减少技能冷却时间");
         Locale.setString("TIP_17","cn","就算无法瞄准，炮塔子弹爆炸所产生的暴风仍可以间接伤害飞行敌人。");
         Locale.setString("TIP_18","cn","使用军营或呼叫援军来孤立麻烦的敌人。");
         Locale.setString("TIP_19","cn","提升特定的技能后野蛮人士兵将可以攻击飞行敌人。");
         Locale.setString("TIP_20","cn","地元素非常的坚硬，而且每次攻击都可以对敌人造成范围伤害。");
         Locale.setString("TIP_21","cn","使用数字键[1]和[2]来快速选择技能。");
         Locale.setString("STAR_WIN_1","cn","");
         Locale.setString("STAR_WIN_2","cn","");
         Locale.setString("STAR_WIN_3","cn","");
         Locale.setString("TUTORIAL_INTRO_BUTTON_CANCEL","cn","跳过说明\n立刻开战！");
         Locale.setString("TUTORIAL_INTRO_BUTTON_NEXT","cn","进入教学\n模式");
         Locale.setString("TUTORIAL_BASICS_BUTTON_CANCEL","cn","跳过说明\n立刻开战！");
         Locale.setString("TUTORIAL_BASICS_BUTTON_NEXT","cn","进入教学\n模式");
         Locale.setString("TUTORIAL_TOWERS_BUTTON_CANCEL","cn","跳过说明\n立刻开战！");
         Locale.setString("TUTORIAL_TOWERS_BUTTON_NEXT","cn","进入教学\n模式");
         Locale.setString("SPECIAL_ELF_REPAIR_NAME","cn","修复");
         Locale.setString("SPECIAL_ELF_REPAIR_DESCRIPTION","cn","这栋建筑物曾是妖精战士们的训练场所。");
         Locale.setString("SPECIAL_ELF_NAME","cn","妖精战士");
         Locale.setString("SPECIAL_ELF_NAME_DESCRIPTION","cn","森林妖精是弓与刀的专家，他们将加入你的部队...只要你付钱的话。");
         Locale.setString("SPECIAL_SASQUASH_REPAIR_NAME","cn","神秘洞窟");
         Locale.setString("SPECIAL_SASQUASH_REPAIR_DESCRIPTION","cn","这个洞窟在好久以前就被冰雪所掩盖...");
         Locale.setString("SPECIAL_SASQUASH_NAME","cn","大脚萨克斯奇");
         Locale.setString("SPECIAL_SASQUASH_DESCRIPTION","cn","传说中萨克斯奇是很乐于助人的，只要你提供他些食物、黄金...或是女人。");
         Locale.setString("SPECIAL_SUNRAY_NAME","cn","日光之塔");
         Locale.setString("SPECIAL_SUNRAY_MAGE_NAME","cn","日光射线");
         Locale.setString("SPECIAL_SUNRAY_MAGE_DESCRIPTION","cn","利用日光能量转为攻击力，需雇用巫师来启动。");
         Locale.setString("SPECIAL_SUNRAY_CROSSHAIR_NAME","cn","发射日光射线");
         Locale.setString("SPECIAL_SUNRAY_CROSSHAIR_DESCRIPTION","cn","对目标敌人发射日光射线。\n\n按下空格键取消。");
         Locale.setString("UPGRADE_ARCHERSUPSALVAGE_NAME","cn","资源回收");
         Locale.setString("UPGRADE_ARCHERSUPSALVAGE_DESCRIPTION","cn","当弓箭塔被售时可以回收90％的金额。");
         Locale.setString("UPGRADE_ARCHERSUPEAGLEEYE_NAME","cn","苍鹰之眼");
         Locale.setString("UPGRADE_ARCHERSUPEAGLEEYE_DESCRIPTION","cn","增加弓箭塔的攻击范围。");
         Locale.setString("UPGRADE_ARCHERSUPPIERCING_NAME","cn","贯穿射击");
         Locale.setString("UPGRADE_ARCHERSUPPIERCING_DESCRIPTION","cn","攻击可以无视敌人铠甲部分的防御力。");
         Locale.setString("UPGRADE_ARCHERSUPFARSHOTS_NAME","cn","远程射击");
         Locale.setString("UPGRADE_ARCHERSUPFARSHOTS_DESCRIPTION","cn","增加弓箭塔的攻击范围。");
         Locale.setString("UPGRADE_ARCHERSUPPRECISION_NAME","cn","精准射击");
         Locale.setString("UPGRADE_ARCHERSUPPRECISION_DESCRIPTION","cn","弓箭塔有机率对敌人造成两倍伤害。");
         Locale.setString("UPGRADE_BARRACKSUPSURVIVAL_NAME","cn","坚实训练");
         Locale.setString("UPGRADE_BARRACKSUPSURVIVAL_DESCRIPTION","cn","提升军营士兵的生命值。");
         Locale.setString("UPGRADE_BARRACKSUPBETTERARMOR_NAME","cn","精良铠甲");
         Locale.setString("UPGRADE_BARRACKSUPBETTERARMOR_DESCRIPTION","cn","改良军营士兵的铠甲，提升防御力。");
         Locale.setString("UPGRADE_BARRACKSUPIMPROVEDDEPLOYMENT_NAME","cn","部署改良");
         Locale.setString("UPGRADE_BARRACKSUPIMPROVEDDEPLOYMENT_DESCRIPTION","cn","增加可设定集结点的最大范围并缩短训练时间。");
         Locale.setString("UPGRADE_BARRACKSUPSURVIVAL2_NAME","cn","耐力训练");
         Locale.setString("UPGRADE_BARRACKSUPSURVIVAL2_DESCRIPTION","cn","军营训练的士兵增加更多的生命值。");
         Locale.setString("UPGRADE_BARRACKSUPBARBEDARMOR_NAME","cn","尖刺护甲");
         Locale.setString("UPGRADE_BARRACKSUPBARBEDARMOR_DESCRIPTION","cn","当士兵遭受攻击时，会对敌人反击一定伤害值回去。\n\n(本技能对援军也适用)");
         Locale.setString("UPGRADE_MAGESUPSPELLREACH_NAME","cn","魔力延伸");
         Locale.setString("UPGRADE_MAGESUPSPELLREACH_DESCRIPTION","cn","增加魔法塔的攻击范围。");
         Locale.setString("UPGRADE_MAGESUPARCANESHATTER_NAME","cn","粉碎秘法");
         Locale.setString("UPGRADE_MAGESUPARCANESHATTER_DESCRIPTION","cn","每次魔法攻击都会破坏敌人部分的铠甲。");
         Locale.setString("UPGRADE_MAGESUPHERMETICSTUDY_NAME","cn","秘室研究");
         Locale.setString("UPGRADE_MAGESUPHERMETICSTUDY_DESCRIPTION","cn","魔法塔的建造与升级费用减少10％。");
         Locale.setString("UPGRADE_MAGESUPEMPOWEREDMAGIC_NAME","cn","强化魔力");
         Locale.setString("UPGRADE_MAGESUPEMPOWEREDMAGIC_DESCRIPTION","cn","增加魔法塔的攻击伤害。");
         Locale.setString("UPGRADE_MAGESUPSLOWCURSE_NAME","cn","迟缓咒术");
         Locale.setString("UPGRADE_MAGESUPSLOWCURSE_DESCRIPTION","cn","魔法攻击会在一定时间内降低敌人一半的移动速度。");
         Locale.setString("UPGRADE_ENGINEERSUPCONCENTRATEDFIRE_NAME","cn","集中火力");
         Locale.setString("UPGRADE_ENGINEERSUPCONCENTRATEDFIRE_DESCRIPTION","cn","增加炮塔的攻击伤害。");
         Locale.setString("UPGRADE_ENGINEERSUPRANGEFINDER_NAME","cn","测距系统");
         Locale.setString("UPGRADE_ENGINEERSUPRANGEFINDER_DESCRIPTION","cn","增加炮塔的攻击范围。");
         Locale.setString("UPGRADE_ENGINEERSUPFIELDLOGISTICS_NAME","cn","后勤补给");
         Locale.setString("UPGRADE_ENGINEERSUPFIELDLOGISTICS_DESCRIPTION","cn","炮塔的建设与升级费用减少10％。");
         Locale.setString("UPGRADE_ENGINEERSUPINDUSTRIALIZATION_NAME","cn","产线制造");
         Locale.setString("UPGRADE_ENGINEERSUPINDUSTRIALIZATION_DESCRIPTION","cn","炮塔的特殊技能花费减少25%。");
         Locale.setString("UPGRADE_ENGINEERSUPEFFICIENCY_NAME","cn","智能瞄准");
         Locale.setString("UPGRADE_ENGINEERSUPEFFICIENCY_DESCRIPTION","cn","炮塔系列的炮弹溅射与连锁闪电伤害不被降低。");
         Locale.setString("UPGRADE_RAINUPBLAZINGSKIES_NAME","cn","炽热天空");
         Locale.setString("UPGRADE_RAINUPBLAZINGSKIES_DESCRIPTION","cn","陨石风暴提升攻击力并额外增加两颗陨石。");
         Locale.setString("UPGRADE_RAINUPSCORCHEDEARTH_NAME","cn","化为焦土");
         Locale.setString("UPGRADE_RAINUPSCORCHEDEARTH_DESCRIPTION","cn","陨石会让地面陷入灼热状态5秒钟来伤害经过的敌人。");
         Locale.setString("UPGRADE_RAINSUPBIGGERANDMEANER_NAME","cn","急速暴烈");
         Locale.setString("UPGRADE_RAINSUPBIGGERANDMEANER_DESCRIPTION","cn","增加陨石风暴的伤害值、提升爆炸半径25%，并缩短冷却时间10秒。");
         Locale.setString("UPGRADE_RAINUPBLAZINGEARTH_NAME","cn","燃烧大地");
         Locale.setString("UPGRADE_RAINUPBLAZINGEARTH_DESCRIPTION","cn","灼热地面的持续时间与伤害加倍，并减少陨石风暴的冷却时间10秒。");
         Locale.setString("UPGRADE_RAINUPCATACLYSM_NAME","cn","天地异变");
         Locale.setString("UPGRADE_RAINUPCATACLYSM_DESCRIPTION","cn","增加陨石风暴的伤害值，并随机在范围外降下陨石造成伤害。");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL1_NAME","cn","粮草补充");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL1_DESCRIPTION","cn","为民兵补充粮草，提升生命值与攻击力。");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL2_NAME","cn","义勇部队");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL2_DESCRIPTION","cn","义勇部队有较高的生命值与较精良的装备。");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL3_NAME","cn","战士部队");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL3_DESCRIPTION","cn","战士部队有更高的生命值与更精良的装备。");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL4_NAME","cn","骑士部队");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL4_DESCRIPTION","cn","骑士部队有最高的生命值与最精良的装备。");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL5_NAME","cn","长矛投掷");
         Locale.setString("UPGRADE_REINFORCEMENTLEVEL5_DESCRIPTION","cn","骑士部队可以对所有敌人投掷长矛进行攻击。");
         Locale.setString("ACHIEVEMENT_UPGRADE_LEVEL3_NAME","cn","全能改造");
         Locale.setString("ACHIEVEMENT_UPGRADE_LEVEL3_DESCRIPTION","cn","将所有防御塔提升到等级3。");
         Locale.setString("ACHIEVEMENT_EASY_TOWER_BUILDER_NAME","cn","建筑工人");
         Locale.setString("ACHIEVEMENT_EASY_TOWER_BUILDER_DESCRIPTION","cn","建造30座防御塔。");
         Locale.setString("ACHIEVEMENT_DARING_NAME","cn","大胆无惧");
         Locale.setString("ACHIEVEMENT_DARING_DESCRIPTION","cn","让10波以上的敌人提早到来。");
         Locale.setString("ACHIEVEMENT_FIRST_BLOOD_NAME","cn","第一滴血");
         Locale.setString("ACHIEVEMENT_FIRST_BLOOD_DESCRIPTION","cn","杀死任一敌人。");
         Locale.setString("ACHIEVEMENT_BLOODLUST_NAME","cn","嗜血狂杀");
         Locale.setString("ACHIEVEMENT_BLOODLUST_DESCRIPTION","cn","消灭500个敌人。");
         Locale.setString("ACHIEVEMENT_WHATS_THAT_NAME","cn","那是什么？");
         Locale.setString("ACHIEVEMENT_WHATS_THAT_DESCRIPTION","cn","开启10个敌人的提示信息。");
         Locale.setString("ACHIEVEMENT_ARMAGGEDON_NAME","cn","世界末日");
         Locale.setString("ACHIEVEMENT_ARMAGGEDON_DESCRIPTION","cn","在同一关卡使用陨石风暴5次以上。");
         Locale.setString("ACHIEVEMENT_EARN15_STARS_NAME","cn","星空闪耀");
         Locale.setString("ACHIEVEMENT_EARN15_STARS_DESCRIPTION","cn","合计获得15颗星。");
         Locale.setString("ACHIEVEMENT_MEDIUM_TOWER_BUILDER_NAME","cn","工程师");
         Locale.setString("ACHIEVEMENT_MEDIUM_TOWER_BUILDER_DESCRIPTION","cn","建造100座防御塔。");
         Locale.setString("ACHIEVEMENT_SPECIALIZATION_NAME","cn","专家");
         Locale.setString("ACHIEVEMENT_SPECIALIZATION_DESCRIPTION","cn","建造全部8种的进阶防御塔。");
         Locale.setString("ACHIEVEMENT_DEFEAT_JUGGERNAUT_NAME","cn","螺帽与螺丝");
         Locale.setString("ACHIEVEMENT_DEFEAT_JUGGERNAUT_DESCRIPTION","cn","击败狂暴魔像。");
         Locale.setString("ACHIEVEMENT_DEFEAT_MOUNTAIN_BOSS_NAME","cn","雪怪死了没？");
         Locale.setString("ACHIEVEMENT_DEFEAT_MOUNTAIN_BOSS_DESCRIPTION","cn","击败大雪怪。");
         Locale.setString("ACHIEVEMENT_SLAYER_NAME","cn","杀手");
         Locale.setString("ACHIEVEMENT_SLAYER_DESCRIPTION","cn","消灭2500个敌人。");
         Locale.setString("ACHIEVEMENT_DEATH_FROM_ABOVE_NAME","cn","天降灾厄");
         Locale.setString("ACHIEVEMENT_DEATH_FROM_ABOVE_DESCRIPTION","cn","使用陨石风暴消灭100个敌人。");
         Locale.setString("ACHIEVEMENT_TACTICIAN_NAME","cn","执行战术");
         Locale.setString("ACHIEVEMENT_TACTICIAN_DESCRIPTION","cn","改变士兵集结点200次");
         Locale.setString("ACHIEVEMENT_EARN30_STARS_NAME","cn","超级玛莉");
         Locale.setString("ACHIEVEMENT_EARN30_STARS_DESCRIPTION","cn","合计获得30颗星。");
         Locale.setString("ACHIEVEMENT_DEFEAT_END_BOSS_NAME","cn","最终决战");
         Locale.setString("ACHIEVEMENT_DEFEAT_END_BOSS_DESCRIPTION","cn","击败恶魔巫师卫兹南。");
         Locale.setString("ACHIEVEMENT_MULTIKILL_NAME","cn","终结者");
         Locale.setString("ACHIEVEMENT_MULTIKILL_DESCRIPTION","cn","消灭10,000个敌人。");
         Locale.setString("ACHIEVEMENT_HARD_TOWER_BUILDER_NAME","cn","建筑师");
         Locale.setString("ACHIEVEMENT_HARD_TOWER_BUILDER_DESCRIPTION","cn","建造150座防御塔");
         Locale.setString("ACHIEVEMENT_DIE_HARD_NAME","cn","不死之躯");
         Locale.setString("ACHIEVEMENT_DIE_HARD_DESCRIPTION","cn","士兵合计回复50,000生命值以上。");
         Locale.setString("ACHIEVEMENT_CANNON_FODDER_NAME","cn","炮灰");
         Locale.setString("ACHIEVEMENT_CANNON_FODDER_DESCRIPTION","cn","牺牲超过1,000个士兵。");
         Locale.setString("ACHIEVEMENT_GI_JOE_NAME","cn","特种部队");
         Locale.setString("ACHIEVEMENT_GI_JOE_DESCRIPTION","cn","训练1,000个士兵。");
         Locale.setString("ACHIEVEMENT_EARN45_STARS_NAME","cn","超级巨星");
         Locale.setString("ACHIEVEMENT_EARN45_STARS_DESCRIPTION","cn","合计获得45个星。");
         Locale.setString("ACHIEVEMENT_FEARLESS_NAME","cn","勇者无惧");
         Locale.setString("ACHIEVEMENT_FEARLESS_DESCRIPTION","cn","让任一关卡的所有敌军提早到来。");
         Locale.setString("ACHIEVEMENT_REAL_STATE_NAME","cn","地产大亨");
         Locale.setString("ACHIEVEMENT_REAL_STATE_DESCRIPTION","cn","售出30座塔。");
         Locale.setString("ACHIEVEMENT_IMPATIENT_NAME","cn","心急如焚");
         Locale.setString("ACHIEVEMENT_IMPATIENT_DESCRIPTION","cn","在下一波图示出现三秒内点击。");
         Locale.setString("ACHIEVEMENT_INDECISIVE_NAME","cn","优柔寡断");
         Locale.setString("ACHIEVEMENT_INDECISIVE_DESCRIPTION","cn","在同一关卡售出5个防御塔。");
         Locale.setString("ACHIEVEMENT_MAX_ELVES_NAME","cn","森林同盟");
         Locale.setString("ACHIEVEMENT_MAX_ELVES_DESCRIPTION","cn","在银橡森林招募妖精战士到数量上限。");
         Locale.setString("ACHIEVEMENT_IMPERIAL_SAVIOUR_NAME","cn","救世英雄");
         Locale.setString("ACHIEVEMENT_IMPERIAL_SAVIOUR_DESCRIPTION","cn","至少三名圣骑士存活通过城塞决战。");
         Locale.setString("ACHIEVEMENT_HENDERSON_NAME","cn","异种友谊");
         Locale.setString("ACHIEVEMENT_HENDERSON_DESCRIPTION","cn","在冰风之谷关卡解放大脚萨克斯奇");
         Locale.setString("ACHIEVEMENT_SUN_BURNER_NAME","cn","日光灼烧");
         Locale.setString("ACHIEVEMENT_SUN_BURNER_DESCRIPTION","cn","发射日光射线20次。");
         Locale.setString("ACHIEVEMENT_BEAM_ME_UP_NAME","cn","史考提，把我传送上去！");
         Locale.setString("ACHIEVEMENT_BEAM_ME_UP_DESCRIPTION","cn","传送250个以上的敌人。");
         Locale.setString("ACHIEVEMENT_AXE_RAINER_NAME","cn","狂斧暴雨");
         Locale.setString("ACHIEVEMENT_AXE_RAINER_DESCRIPTION","cn","投掷超过500个斧头。");
         Locale.setString("ACHIEVEMENT_SNIPER_NAME","cn","来一个杀一个");
         Locale.setString("ACHIEVEMENT_SNIPER_DESCRIPTION","cn","狙击50个敌人");
         Locale.setString("ACHIEVEMENT_TOXICITY_NAME","cn","毒杀");
         Locale.setString("ACHIEVEMENT_TOXICITY_DESCRIPTION","cn","让50个敌人因中毒伤害而亡。");
         Locale.setString("ACHIEVEMENT_ROCKETEER_NAME","cn","火箭狂热者");
         Locale.setString("ACHIEVEMENT_ROCKETEER_DESCRIPTION","cn","发射100个飞弹。");
         Locale.setString("ACHIEVEMENT_SHEPARD_NAME","cn","牧羊人");
         Locale.setString("ACHIEVEMENT_SHEPARD_DESCRIPTION","cn","将50个敌人变为绵羊。");
         Locale.setString("ACHIEVEMENT_DUST_TO_DUST_NAME","cn","尘归尘");
         Locale.setString("ACHIEVEMENT_DUST_TO_DUST_DESCRIPTION","cn","用死亡射线消灭50个以上的敌人。");
         Locale.setString("ACHIEVEMENT_ENTANGLED_NAME","cn","纠缠");
         Locale.setString("ACHIEVEMENT_ENTANGLED_DESCRIPTION","cn","森林之怒合计困住500个敌人以上。");
         Locale.setString("ACHIEVEMENT_ENERGY_NETWORK_NAME","cn","能量网络");
         Locale.setString("ACHIEVEMENT_ENERGY_NETWORK_DESCRIPTION","cn","在任一关卡建造四座特斯拉x104塔");
         Locale.setString("ACHIEVEMENT_ELEMENTALIST_NAME","cn","元素使者");
         Locale.setString("ACHIEVEMENT_ELEMENTALIST_DESCRIPTION","cn","在任一关卡召唤5个岩石元素。");
         Locale.setString("ACHIEVEMENT_BARBARIAN_RUSH_NAME","cn","这下你们开心了吧？");
         Locale.setString("ACHIEVEMENT_BARBARIAN_RUSH_SHORT_NAME","cn","这下你们开心了吧？");
         Locale.setString("ACHIEVEMENT_BARBARIAN_RUSH_DESCRIPTION","cn","让单一野蛮人击杀10个敌人。");
         Locale.setString("ACHIEVEMENT_CLUSTERED_NAME","cn","集束炸弹");
         Locale.setString("ACHIEVEMENT_CLUSTERED_DESCRIPTION","cn","进行1,000以上范围轰炸。");
         Locale.setString("ACHIEVEMENT_ACDC_NAME","cn","AC/DC");
         Locale.setString("ACHIEVEMENT_ACDC_DESCRIPTION","cn","使用电流消灭300个敌人以上。");
         Locale.setString("ACHIEVEMENT_MEDIC_NAME","cn","医护兵");
         Locale.setString("ACHIEVEMENT_MEDIC_DESCRIPTION","cn","圣骑士总共治疗7,000生命值以上。");
         Locale.setString("ACHIEVEMENT_HOLY_CHORUS_NAME","cn","圣音");
         Locale.setString("ACHIEVEMENT_HOLY_CHORUS_DESCRIPTION","cn","使用100次神圣攻击。");
         Locale.setString("ACHIEVEMENT_SHEEP_KILLER_NAME","cn","大野狼");
         Locale.setString("ACHIEVEMENT_SHEEP_KILLER_DESCRIPTION","cn","靠自己的双手杀掉10只绵羊。");
         Locale.setString("ACHIEVEMENT_CATCH_A_FISH_NAME","cn","双子河钓客");
         Locale.setString("ACHIEVEMENT_CATCH_A_FISH_DESCRIPTION","cn","在双子河抓到一条鱼。");
         Locale.setString("ACHIEVEMENT_GREAT_DEFENDER_NAME","cn","名将");
         Locale.setString("ACHIEVEMENT_GREAT_DEFENDER_DESCRIPTION","cn","完成所有普通难度的战役模式。");
         Locale.setString("ACHIEVEMENT_HEROIC_DEFENDER_NAME","cn","英雄");
         Locale.setString("ACHIEVEMENT_HEROIC_DEFENDER_DESCRIPTION","cn","完成所有普通难度的英雄模式。");
         Locale.setString("ACHIEVEMENT_IRON_DEFENDER_NAME","cn","铁血传奇");
         Locale.setString("ACHIEVEMENT_IRON_DEFENDER_DESCRIPTION","cn","完成所有普通难度的铁血模式。");
         Locale.setString("ACHIEVEMENT_FREE_FREDO_NAME","cn","逃吧！佛雷多！");
         Locale.setString("ACHIEVEMENT_FREE_FREDO_DESCRIPTION","cn","帮助佛雷多逃走。");
         Locale.setString("ACHIEVEMENT_DEFEAT_SARELGAZ_BOSS_NAME","cn","蜘蛛克星");
         Locale.setString("ACHIEVEMENT_DEFEAT_SARELGAZ_BOSS_DESCRIPTION","cn","击败蜘蛛女王萨格雷兹与她的手下。");
         Locale.setString("ACHIEVEMENT_DEFEAT_GULTHAK_BOSS_NAME","cn","兽人必须死");
         Locale.setString("ACHIEVEMENT_DEFEAT_GULTHAK_BOSS_DESCRIPTION","cn","击败兽人酋长古拉克与他的手下。");
         Locale.setString("ACHIEVEMENT_DEFEAT_GREENMUK_BOSS_NAME","cn","樵夫");
         Locale.setString("ACHIEVEMENT_DEFEAT_GREENMUK_BOSS_DESCRIPTION","cn","击败腐森之心与他的爪牙们。");
         Locale.setString("ACHIEVEMENT_HERO_MEDIUM_NAME","cn","利尼雷亚冠军");
         Locale.setString("ACHIEVEMENT_HERO_MEDIUM_DESCRIPTION","cn","将任一英雄提升至等级5");
         Locale.setString("ACHIEVEMENT_HERO_HARD_NAME","cn","利尼雷亚传奇");
         Locale.setString("ACHIEVEMENT_HERO_HARD_DESCRIPTION","cn","将任一英雄提升至最高等级");
         Locale.setString("ACHIEVEMENT_DEFEAT_BANDIT_BOSS_NAME","cn","我就是正义！");
         Locale.setString("ACHIEVEMENT_DEFEAT_BANDIT_BOSS_DESCRIPTION","cn","成功阻止金霸王逃亡。");
         Locale.setString("MENU_BOTTOM_ATTACK_NAME","cn","攻击");
         Locale.setString("MENU_BOTTOM_ATTACK_DESCRIPTION","cn","攻击伤害");
         Locale.setString("MENU_BOTTOM_RELOAD_NAME","cn","攻击间隔");
         Locale.setString("MENU_BOTTOM_RELOAD_DESCRIPTION","cn","攻击间隔");
         Locale.setString("MENU_BOTTOM_RANGE_NAME","cn","范围");
         Locale.setString("MENU_BOTTOM_RANGE_DESCRIPTION","cn","攻击范围");
         Locale.setString("MENU_BOTTOM_HEALTH_SINGLE_NAME","cn","生命值");
         Locale.setString("MENU_BOTTOM_HEALTH_SINGLE_DESCRIPTION","cn","单位生命值");
         Locale.setString("MENU_BOTTOM_HEALTH_NAME","cn","生命值");
         Locale.setString("MENU_BOTTOM_HEALTH_DESCRIPTION","cn","当前生命值/生命值上限");
         Locale.setString("MENU_BOTTOM_ARMOR_NAME","cn","铠甲");
         Locale.setString("MENU_BOTTOM_ARMOR_DESCRIPTION","cn","铠甲");
         Locale.setString("MENU_BOTTOM_MAGIC_ARMOR_NAME","cn","魔法抗性");
         Locale.setString("MENU_BOTTOM_MAGIC_ARMOR_DESCRIPTION","cn","魔法抗性");
         Locale.setString("MENU_BOTTOM_RESPAWN_NAME","cn","重生");
         Locale.setString("MENU_BOTTOM_RESPAWN_DESCRIPTION","cn","重生时间");
         Locale.setString("MENU_BOTTOM_ARMOR_ENEMY_NAME","cn","重装部队");
         Locale.setString("MENU_BOTTOM_ARMOR_ENEMY_DESCRIPTION","cn","物理铠甲");
         Locale.setString("MENU_BOTTOM_COST_NAME","cn","代价");
         Locale.setString("MENU_BOTTOM_COST_DESCRIPTION","cn","敌人通过防守线后我方失去的生命。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_HEALTH_NAME","cn","生命值");
         Locale.setString("ENCYCLOPEDIA_ENEMY_HEALTH_DESCRIPTION","cn","所能承受的伤害上限。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ATTACK_NAME","cn","攻击伤害");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ATTACK_DESCRIPTION","cn","攻击时可以对敌人造成多少伤害。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ARMOR_NAME","cn","铠甲等级");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ARMOR_DESCRIPTION","cn","铠甲可以减少所受到的物理伤害。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ARMOR_MAGIC_NAME","cn","魔法抗性");
         Locale.setString("ENCYCLOPEDIA_ENEMY_ARMOR_MAGIC_DESCRIPTION","cn","魔法抗性可以减少所受到的法术伤害。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_SPEED_NAME","cn","速度");
         Locale.setString("ENCYCLOPEDIA_ENEMY_SPEED_DESCRIPTION","cn","角色的移动速度。");
         Locale.setString("ENCYCLOPEDIA_ENEMY_COST_NAME","cn","代价");
         Locale.setString("ENCYCLOPEDIA_ENEMY_COST_DESCRIPTION","cn","敌人通过防守线后我方失去的生命。");
         Locale.setString("ENCYCLOPEDIA_TOWER_ATTACK_NAME","cn","攻击伤害");
         Locale.setString("ENCYCLOPEDIA_TOWER_ATTACK_DESCRIPTION","cn","攻击时所制造的伤害值。");
         Locale.setString("ENCYCLOPEDIA_TOWER_RELOAD_NAME","cn","攻击间隔");
         Locale.setString("ENCYCLOPEDIA_TOWER_RELOAD_DESCRIPTION","cn","两次攻击间隔的时间");
         Locale.setString("ENCYCLOPEDIA_TOWER_RANGE_NAME","cn","攻击范围");
         Locale.setString("ENCYCLOPEDIA_TOWER_RANGE_DESCRIPTION","cn","防御塔可以攻击到的最远范围。");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_HEALTH_NAME","cn","生命值");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_HEALTH_DESCRIPTION","cn","所能承受的伤害上限。");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_ATTACK_NAME","cn","攻击伤害");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_ATTACK_DESCRIPTION","cn","攻击时可以对敌人造成多少伤害。");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_ARMOR_NAME","cn","铠甲等级");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_ARMOR_DESCRIPTION","cn","铠甲可以减少所受到的物理伤害。");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_RESPAWN_NAME","cn","训练时间");
         Locale.setString("ENCYCLOPEDIA_TOWER_SOLDIER_RESPAWN_DESCRIPTION","cn","训练新士兵所需要的时间。");
         Locale.setString("LEVEL_SELECT_TOOLTIP_WAVE_HEROIC_NAME","cn","敌军战术");
         Locale.setString("LEVEL_SELECT_TOOLTIP_WAVE_HEROIC_DESCRIPTION","cn","六波精锐攻击。");
         Locale.setString("LEVEL_SELECT_TOOLTIP_WAVE_IRON_NAME","cn","敌军战术");
         Locale.setString("LEVEL_SELECT_TOOLTIP_WAVE_IRON_DESCRIPTION","cn","一波总攻击。");
         Locale.setString("LEVEL_SELECT_TOOLTIP_LIVES_NAME","cn","生命值");
         Locale.setString("LEVEL_SELECT_TOOLTIP_LIVES_DESCRIPTION","cn","你在本模式所拥有的生命值。");
         Locale.setString("LEVEL_SELECT_TOOLTIP_UPGRADES_NAME","cn","技能限制");
         Locale.setString("LEVEL_SELECT_TOOLTIP_UPGRADES_DESCRIPTION","cn","无法使用等级限制以上的技能。");
         Locale.setString("LEVEL_SELECT_TOOLTIP_TOWERS_NAME","cn","建造限制");
         Locale.setString("LEVEL_SELECT_TOOLTIP_TOWERS_DESCRIPTION","cn","你在本模式建造的限制列表。");
         Locale.setString("HERO_PALADIN_NAME","cn","杰拉尔德爵士");
         Locale.setString("HERO_RIFLEMAN_NAME","cn","矮人火鎗手波林");
         Locale.setString("HERO_ARCHER_NAME","cn","疾风的奥雷莉亚");
         Locale.setString("HERO_REINFORCEMENT_NAME","cn","愤怒之锤马里克");
         Locale.setString("HERO_MAGE_NAME","cn","魔力之刃马格努斯");
         Locale.setString("HERO_FIRE_NAME","cn","炎之魔神");
         Locale.setString("HERO_ARCHER_WILDCAT_NAME","cn","小野猫");
         Locale.setString("HERO_MAGE_SHADOW_NAME","cn","马格努斯的幻影");
         Locale.setString("HERO_DENAS_NAME","cn","国王 迪纳斯");
         Locale.setString("HERO_PALADIN_DESCRIPTION","cn","善人的守护者、坏人的梦魇，保护无辜的民众、消灭邪恶的存在！光之守护者杰拉尔德是利尼雷亚军队中最传奇的一章！");
         Locale.setString("HERO_RIFLEMAN_DESCRIPTION","cn","就算闪电都比不上他的射击来得迅捷！\n铺天盖地的枪林弹雨、与不知在何处的地雷，将使敌人们步步惊心！");
         Locale.setString("HERO_ARCHER_DESCRIPTION","cn","她幽静如夜晚、轻盈如羽翼，美丽而致命...。许多人因她的迷人目光而陷于魅惑，但更多人因她的致命箭术而死于非命。");
         Locale.setString("HERO_REINFORCEMENT_DESCRIPTION","cn","来自于很远、很远的地方...，是位感觉敏锐、意志坚强并拥有强大力量的英雄。");
         Locale.setString("HERO_MAGE_DESCRIPTION","cn","藉由对秘术与知识的渴求，他习得了利尼雷亚的神秘力量，并藉此施展了各种魔法来消灭与混乱敌人！");
         Locale.setString("HERO_FIRE_DESCRIPTION","cn","以星辰焰火烧尽王国的敌人！以地狱业火消灭所有的邪恶！以愤怒烈焰开拓完全的胜利！");
         Locale.setString("HERO_DENAS_DESCRIPTION","cn","陛下的威严为士兵们带来了勇气与战力！国王万岁！");
         Locale.setString("HERO_PALADIN_SPECIAL","cn","鼓舞、惩戒之盾");
         Locale.setString("HERO_RIFLEMAN_SPECIAL","cn","地雷陷阱、焦油炸弹");
         Locale.setString("HERO_ARCHER_SPECIAL","cn","多重射击、野性呼唤");
         Locale.setString("HERO_REINFORCEMENT_SPECIAL","cn","粉碎之锤、地震");
         Locale.setString("HERO_MAGE_SPECIAL","cn","幻影、秘法风暴");
         Locale.setString("HERO_FIRE_SPECIAL","cn","火焰波、暴焰冲击");
         Locale.setString("HERO_DENAS_SPECIAL","cn","皇家敕令、火力支持");
         Locale.setString("TOWER_BARRACKS_NAME","es","Barracas");
         Locale.setString("TOWER_BARRACKS_DESCRIPTION","es","Esta es la barracaaa del de mkombat");
         Locale.setString("TOWER_ARCHERS_NAME","es","Arqueros");
         Locale.setString("TOWER_ARCHERS_DESCRIPTION","es","Esta tira flechitas");
         Locale.setString("TOWER_ENGINEERS_NAME","es","Ingenieros");
         Locale.setString("TOWER_ENGINEERS_DESCRIPTION","es","Son los genieros que estan re in");
         Locale.setString("TOWER_MAGES_NAME","es","Magos");
         Locale.setString("TOWER_MAGES_DESCRIPTION","es","Esta es la torre de los magos viteh");
         Locale.setDefaultLang("cn");
      }
      
      public function createMissileParticlesPool() : void
      {
         var _loc1_:MissileParticle = null;
         this.missileParticlesPool = new Dictionary();
         var _loc2_:int = 0;
         while(_loc2_ < this.missileParticlesMax)
         {
            _loc1_ = new MissileParticle();
            this.missileParticlesPool[_loc1_] = _loc1_;
            _loc2_++;
         }
      }
      
      public function createFireballParticlesPool() : void
      {
         var _loc1_:FireballParticle = null;
         this.fireballParticlesPool = new Dictionary();
         var _loc2_:int = 0;
         while(_loc2_ < this.fireballParticlesMax)
         {
            _loc1_ = new FireballParticle();
            this.fireballParticlesPool[_loc1_] = _loc1_;
            _loc2_++;
         }
      }
      
      public function createVeznanParticlesPool() : void
      {
         var _loc1_:VeznanSoulParticle = null;
         this.veznanParticlesPool = new Dictionary();
         var _loc2_:int = 0;
         while(_loc2_ < this.veznanParticlesMax)
         {
            _loc1_ = new VeznanSoulParticle();
            this.veznanParticlesPool[_loc1_] = _loc1_;
            _loc2_++;
         }
      }
   }
}
